Shader "Back position" {
SubShader { 
 Pass {
  Name "FORWARD"
  Tags { "LIGHTMODE"="ForwardBase" }
  ZTest Always
  ZWrite Off
  Cull Front
  Blend SrcAlpha OneMinusSrcAlpha
  AlphaTest Greater 0
  ColorMask RGB
Program "vp" {
SubProgram "d3d11 " {
Keywords { "DIRECTIONAL" "LIGHTMAP_OFF" "DIRLIGHTMAP_OFF" }
Bind "vertex" Vertex
Bind "color" Color
Bind "normal" Normal
ConstBuffer "UnityPerCamera" 128
Vector 80 [_ProjectionParams]
ConstBuffer "UnityLighting" 400
Vector 288 [unity_SHAr]
Vector 304 [unity_SHAg]
Vector 320 [unity_SHAb]
Vector 336 [unity_SHBr]
Vector 352 [unity_SHBg]
Vector 368 [unity_SHBb]
Vector 384 [unity_SHC]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
Matrix 192 [_Object2World]
Vector 320 [unity_Scale]
BindCB  "UnityPerCamera" 0
BindCB  "UnityLighting" 1
BindCB  "UnityPerDraw" 2
"vs_5_0
eefiecedecipinngdiefcfeehbheeoeopmhbkenlabaaaaaabeagaaaaadaaaaaa
cmaaaaaapeaaaaaajeabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapaaaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapaaaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheojiaaaaaaafaaaaaa
aiaaaaaaiaaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaimaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaapaaaaaaimaaaaaaabaaaaaaaaaaaaaa
adaaaaaaacaaaaaaahaiaaaaimaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaa
ahaiaaaaimaaaaaaadaaaaaaaaaaaaaaadaaaaaaaeaaaaaaahaiaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaklklklfdeieffihiaeaaaafaaaabaa
boabaaaagkaiaaabfjaaaaaeegiocaaaaaaaaaaaagaaaaaafjaaaaaeegiocaaa
abaaaaaabjaaaaaafjaaaaaeegiocaaaacaaaaaabfaaaaaafpaaaaadpcbabaaa
aaaaaaaafpaaaaadhcbabaaaacaaaaaaghaaaaaepccabaaaaaaaaaaaabaaaaaa
gfaaaaadpccabaaaabaaaaaagfaaaaadhccabaaaacaaaaaagfaaaaadhccabaaa
adaaaaaagfaaaaadhccabaaaaeaaaaaagiaaaaacaeaaaaaadiaaaaaipcaabaaa
aaaaaaaafgbfbaaaaaaaaaaaegiocaaaacaaaaaaabaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaacaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaacaaaaaaacaaaaaakgbkbaaaaaaaaaaa
egaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaacaaaaaaadaaaaaa
pgbpbaaaaaaaaaaaegaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaa
aaaaaaaadiaaaaaiccaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaaaaaaaaaaa
afaaaaaadiaaaaakncaabaaaabaaaaaaagahbaaaaaaaaaaaaceaaaaaaaaaaadp
aaaaaaaaaaaaaadpaaaaaadpdgaaaaafmccabaaaabaaaaaakgaobaaaaaaaaaaa
aaaaaaahdccabaaaabaaaaaakgakbaaaabaaaaaamgaabaaaabaaaaaadiaaaaai
hcaabaaaaaaaaaaafgbfbaaaaaaaaaaaegiccaaaacaaaaaaanaaaaaadcaaaaak
hcaabaaaaaaaaaaaegiccaaaacaaaaaaamaaaaaaagbabaaaaaaaaaaaegacbaaa
aaaaaaaadcaaaaakhcaabaaaaaaaaaaaegiccaaaacaaaaaaaoaaaaaakgbkbaaa
aaaaaaaaegacbaaaaaaaaaaadcaaaaakhccabaaaacaaaaaaegiccaaaacaaaaaa
apaaaaaapgbpbaaaaaaaaaaaegacbaaaaaaaaaaadiaaaaaihcaabaaaaaaaaaaa
egbcbaaaacaaaaaapgipcaaaacaaaaaabeaaaaaadiaaaaaihcaabaaaabaaaaaa
fgafbaaaaaaaaaaaegiccaaaacaaaaaaanaaaaaadcaaaaaklcaabaaaaaaaaaaa
egiicaaaacaaaaaaamaaaaaaagaabaaaaaaaaaaaegaibaaaabaaaaaadcaaaaak
hcaabaaaaaaaaaaaegiccaaaacaaaaaaaoaaaaaakgakbaaaaaaaaaaaegadbaaa
aaaaaaaadgaaaaafhccabaaaadaaaaaaegacbaaaaaaaaaaadgaaaaaficaabaaa
aaaaaaaaabeaaaaaaaaaiadpbbaaaaaibcaabaaaabaaaaaaegiocaaaabaaaaaa
bcaaaaaaegaobaaaaaaaaaaabbaaaaaiccaabaaaabaaaaaaegiocaaaabaaaaaa
bdaaaaaaegaobaaaaaaaaaaabbaaaaaiecaabaaaabaaaaaaegiocaaaabaaaaaa
beaaaaaaegaobaaaaaaaaaaadiaaaaahpcaabaaaacaaaaaajgacbaaaaaaaaaaa
egakbaaaaaaaaaaabbaaaaaibcaabaaaadaaaaaaegiocaaaabaaaaaabfaaaaaa
egaobaaaacaaaaaabbaaaaaiccaabaaaadaaaaaaegiocaaaabaaaaaabgaaaaaa
egaobaaaacaaaaaabbaaaaaiecaabaaaadaaaaaaegiocaaaabaaaaaabhaaaaaa
egaobaaaacaaaaaaaaaaaaahhcaabaaaabaaaaaaegacbaaaabaaaaaaegacbaaa
adaaaaaadiaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaabkaabaaaaaaaaaaa
dcaaaaakbcaabaaaaaaaaaaaakaabaaaaaaaaaaaakaabaaaaaaaaaaabkaabaia
ebaaaaaaaaaaaaaadcaaaaakhccabaaaaeaaaaaaegiccaaaabaaaaaabiaaaaaa
agaabaaaaaaaaaaaegacbaaaabaaaaaadoaaaaab"
}
SubProgram "d3d11 " {
Keywords { "DIRECTIONAL" "LIGHTMAP_ON" "DIRLIGHTMAP_OFF" }
Bind "vertex" Vertex
Bind "color" Color
Bind "texcoord1" TexCoord1
ConstBuffer "$Globals" 208
Vector 192 [unity_LightmapST]
ConstBuffer "UnityPerCamera" 128
Vector 80 [_ProjectionParams]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
Matrix 192 [_Object2World]
BindCB  "$Globals" 0
BindCB  "UnityPerCamera" 1
BindCB  "UnityPerDraw" 2
"vs_5_0
eefiecedgdhiccmfoafkpmifjabbhmnieamfbdbhabaaaaaaaaaeaaaaadaaaaaa
cmaaaaaapeaaaaaahmabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahaaaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapaaaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapadaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapaaaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheoiaaaaaaaaeaaaaaa
aiaaaaaagiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaapaaaaaaheaaaaaaabaaaaaaaaaaaaaa
adaaaaaaacaaaaaaahaiaaaaheaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaa
adamaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfceeaaklklklfdeieffi
hmacaaaafaaaabaajpaaaaaagkaiaaabfjaaaaaeegiocaaaaaaaaaaaanaaaaaa
fjaaaaaeegiocaaaabaaaaaaagaaaaaafjaaaaaeegiocaaaacaaaaaabaaaaaaa
fpaaaaadpcbabaaaaaaaaaaafpaaaaaddcbabaaaaeaaaaaaghaaaaaepccabaaa
aaaaaaaaabaaaaaagfaaaaadpccabaaaabaaaaaagfaaaaadhccabaaaacaaaaaa
gfaaaaaddccabaaaadaaaaaagiaaaaacacaaaaaadiaaaaaipcaabaaaaaaaaaaa
fgbfbaaaaaaaaaaaegiocaaaacaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaa
egiocaaaacaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaak
pcaabaaaaaaaaaaaegiocaaaacaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaa
aaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaacaaaaaaadaaaaaapgbpbaaa
aaaaaaaaegaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaa
diaaaaaiccaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaaaabaaaaaaafaaaaaa
diaaaaakncaabaaaabaaaaaaagahbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaaaa
aaaaaadpaaaaaadpdgaaaaafmccabaaaabaaaaaakgaobaaaaaaaaaaaaaaaaaah
dccabaaaabaaaaaakgakbaaaabaaaaaamgaabaaaabaaaaaadiaaaaaihcaabaaa
aaaaaaaafgbfbaaaaaaaaaaaegiccaaaacaaaaaaanaaaaaadcaaaaakhcaabaaa
aaaaaaaaegiccaaaacaaaaaaamaaaaaaagbabaaaaaaaaaaaegacbaaaaaaaaaaa
dcaaaaakhcaabaaaaaaaaaaaegiccaaaacaaaaaaaoaaaaaakgbkbaaaaaaaaaaa
egacbaaaaaaaaaaadcaaaaakhccabaaaacaaaaaaegiccaaaacaaaaaaapaaaaaa
pgbpbaaaaaaaaaaaegacbaaaaaaaaaaadcaaaaaldccabaaaadaaaaaaegbabaaa
aeaaaaaaegiacaaaaaaaaaaaamaaaaaaogikcaaaaaaaaaaaamaaaaaadoaaaaab
"
}
SubProgram "d3d11 " {
Keywords { "DIRECTIONAL" "LIGHTMAP_OFF" "DIRLIGHTMAP_OFF" "VERTEXLIGHT_ON" }
Bind "vertex" Vertex
Bind "color" Color
Bind "normal" Normal
ConstBuffer "UnityPerCamera" 128
Vector 80 [_ProjectionParams]
ConstBuffer "UnityLighting" 400
Vector 32 [unity_4LightPosX0]
Vector 48 [unity_4LightPosY0]
Vector 64 [unity_4LightPosZ0]
Vector 80 [unity_4LightAtten0]
Vector 96 [unity_LightColor0]
Vector 112 [unity_LightColor1]
Vector 128 [unity_LightColor2]
Vector 144 [unity_LightColor3]
Vector 288 [unity_SHAr]
Vector 304 [unity_SHAg]
Vector 320 [unity_SHAb]
Vector 336 [unity_SHBr]
Vector 352 [unity_SHBg]
Vector 368 [unity_SHBb]
Vector 384 [unity_SHC]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
Matrix 192 [_Object2World]
Vector 320 [unity_Scale]
BindCB  "UnityPerCamera" 0
BindCB  "UnityLighting" 1
BindCB  "UnityPerDraw" 2
"vs_5_0
eefiecedmahpcphdjgomcmmmneediopchnnicnbgabaaaaaaoaaiaaaaadaaaaaa
cmaaaaaapeaaaaaajeabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapaaaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapaaaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheojiaaaaaaafaaaaaa
aiaaaaaaiaaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaimaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaapaaaaaaimaaaaaaabaaaaaaaaaaaaaa
adaaaaaaacaaaaaaahaiaaaaimaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaa
ahaiaaaaimaaaaaaadaaaaaaaaaaaaaaadaaaaaaaeaaaaaaahaiaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaklklklfdeieffieeahaaaafaaaabaa
nbabaaaagkaiaaabfjaaaaaeegiocaaaaaaaaaaaagaaaaaafjaaaaaeegiocaaa
abaaaaaabjaaaaaafjaaaaaeegiocaaaacaaaaaabfaaaaaafpaaaaadpcbabaaa
aaaaaaaafpaaaaadhcbabaaaacaaaaaaghaaaaaepccabaaaaaaaaaaaabaaaaaa
gfaaaaadpccabaaaabaaaaaagfaaaaadhccabaaaacaaaaaagfaaaaadhccabaaa
adaaaaaagfaaaaadhccabaaaaeaaaaaagiaaaaacagaaaaaadiaaaaaipcaabaaa
aaaaaaaafgbfbaaaaaaaaaaaegiocaaaacaaaaaaabaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaacaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaacaaaaaaacaaaaaakgbkbaaaaaaaaaaa
egaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaacaaaaaaadaaaaaa
pgbpbaaaaaaaaaaaegaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaa
aaaaaaaadiaaaaaiccaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaaaaaaaaaaa
afaaaaaadiaaaaakncaabaaaabaaaaaaagahbaaaaaaaaaaaaceaaaaaaaaaaadp
aaaaaaaaaaaaaadpaaaaaadpdgaaaaafmccabaaaabaaaaaakgaobaaaaaaaaaaa
aaaaaaahdccabaaaabaaaaaakgakbaaaabaaaaaamgaabaaaabaaaaaadiaaaaai
hcaabaaaaaaaaaaafgbfbaaaaaaaaaaaegiccaaaacaaaaaaanaaaaaadcaaaaak
hcaabaaaaaaaaaaaegiccaaaacaaaaaaamaaaaaaagbabaaaaaaaaaaaegacbaaa
aaaaaaaadcaaaaakhcaabaaaaaaaaaaaegiccaaaacaaaaaaaoaaaaaakgbkbaaa
aaaaaaaaegacbaaaaaaaaaaadcaaaaakhcaabaaaaaaaaaaaegiccaaaacaaaaaa
apaaaaaapgbpbaaaaaaaaaaaegacbaaaaaaaaaaadgaaaaafhccabaaaacaaaaaa
egacbaaaaaaaaaaadiaaaaaihcaabaaaabaaaaaaegbcbaaaacaaaaaapgipcaaa
acaaaaaabeaaaaaadiaaaaaihcaabaaaacaaaaaafgafbaaaabaaaaaaegiccaaa
acaaaaaaanaaaaaadcaaaaaklcaabaaaabaaaaaaegiicaaaacaaaaaaamaaaaaa
agaabaaaabaaaaaaegaibaaaacaaaaaadcaaaaakhcaabaaaabaaaaaaegiccaaa
acaaaaaaaoaaaaaakgakbaaaabaaaaaaegadbaaaabaaaaaadgaaaaafhccabaaa
adaaaaaaegacbaaaabaaaaaadgaaaaaficaabaaaabaaaaaaabeaaaaaaaaaiadp
bbaaaaaibcaabaaaacaaaaaaegiocaaaabaaaaaabcaaaaaaegaobaaaabaaaaaa
bbaaaaaiccaabaaaacaaaaaaegiocaaaabaaaaaabdaaaaaaegaobaaaabaaaaaa
bbaaaaaiecaabaaaacaaaaaaegiocaaaabaaaaaabeaaaaaaegaobaaaabaaaaaa
diaaaaahpcaabaaaadaaaaaajgacbaaaabaaaaaaegakbaaaabaaaaaabbaaaaai
bcaabaaaaeaaaaaaegiocaaaabaaaaaabfaaaaaaegaobaaaadaaaaaabbaaaaai
ccaabaaaaeaaaaaaegiocaaaabaaaaaabgaaaaaaegaobaaaadaaaaaabbaaaaai
ecaabaaaaeaaaaaaegiocaaaabaaaaaabhaaaaaaegaobaaaadaaaaaaaaaaaaah
hcaabaaaacaaaaaaegacbaaaacaaaaaaegacbaaaaeaaaaaadiaaaaahicaabaaa
aaaaaaaabkaabaaaabaaaaaabkaabaaaabaaaaaadcaaaaakicaabaaaaaaaaaaa
akaabaaaabaaaaaaakaabaaaabaaaaaadkaabaiaebaaaaaaaaaaaaaadcaaaaak
hcaabaaaacaaaaaaegiccaaaabaaaaaabiaaaaaapgapbaaaaaaaaaaaegacbaaa
acaaaaaaaaaaaaajpcaabaaaadaaaaaafgafbaiaebaaaaaaaaaaaaaaegiocaaa
abaaaaaaadaaaaaadiaaaaahpcaabaaaaeaaaaaafgafbaaaabaaaaaaegaobaaa
adaaaaaadiaaaaahpcaabaaaadaaaaaaegaobaaaadaaaaaaegaobaaaadaaaaaa
aaaaaaajpcaabaaaafaaaaaaagaabaiaebaaaaaaaaaaaaaaegiocaaaabaaaaaa
acaaaaaaaaaaaaajpcaabaaaaaaaaaaakgakbaiaebaaaaaaaaaaaaaaegiocaaa
abaaaaaaaeaaaaaadcaaaaajpcaabaaaaeaaaaaaegaobaaaafaaaaaaagaabaaa
abaaaaaaegaobaaaaeaaaaaadcaaaaajpcaabaaaadaaaaaaegaobaaaafaaaaaa
egaobaaaafaaaaaaegaobaaaadaaaaaadcaaaaajpcaabaaaadaaaaaaegaobaaa
aaaaaaaaegaobaaaaaaaaaaaegaobaaaadaaaaaadcaaaaajpcaabaaaaaaaaaaa
egaobaaaaaaaaaaakgakbaaaabaaaaaaegaobaaaaeaaaaaaeeaaaaafpcaabaaa
abaaaaaaegaobaaaadaaaaaadcaaaaanpcaabaaaadaaaaaaegaobaaaadaaaaaa
egiocaaaabaaaaaaafaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaiadp
aoaaaaakpcaabaaaadaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaiadp
egaobaaaadaaaaaadiaaaaahpcaabaaaaaaaaaaaegaobaaaaaaaaaaaegaobaaa
abaaaaaadeaaaaakpcaabaaaaaaaaaaaegaobaaaaaaaaaaaaceaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaadiaaaaahpcaabaaaaaaaaaaaegaobaaaadaaaaaa
egaobaaaaaaaaaaadiaaaaaihcaabaaaabaaaaaafgafbaaaaaaaaaaaegiccaaa
abaaaaaaahaaaaaadcaaaaakhcaabaaaabaaaaaaegiccaaaabaaaaaaagaaaaaa
agaabaaaaaaaaaaaegacbaaaabaaaaaadcaaaaakhcaabaaaaaaaaaaaegiccaaa
abaaaaaaaiaaaaaakgakbaaaaaaaaaaaegacbaaaabaaaaaadcaaaaakhcaabaaa
aaaaaaaaegiccaaaabaaaaaaajaaaaaapgapbaaaaaaaaaaaegacbaaaaaaaaaaa
aaaaaaahhccabaaaaeaaaaaaegacbaaaaaaaaaaaegacbaaaacaaaaaadoaaaaab
"
}
}
Program "fp" {
SubProgram "d3d11 " {
Keywords { "DIRECTIONAL" "LIGHTMAP_OFF" "DIRLIGHTMAP_OFF" }
SetTexture 0 [_CameraDepthTexture] 2D 1
SetTexture 1 [_Background] 2D 2
SetTexture 2 [Volume] 3D 0
ConstBuffer "$Globals" 192
Vector 48 [screenCorner]
Vector 64 [cameraUp]
Vector 80 [cameraRight]
Vector 96 [cameraWorldSize]
Float 112 [StepSize]
Vector 128 [worldOrigin]
Float 144 [halfWorldSize]
Float 148 [transparency]
Vector 160 [bored]
Float 176 [minF]
Float 180 [maxF]
ConstBuffer "UnityPerCamera" 128
Vector 64 [_WorldSpaceCameraPos] 3
Vector 112 [_ZBufferParams]
BindCB  "$Globals" 0
BindCB  "UnityPerCamera" 1
"ps_5_0
eefiecedffhpadkbcnalldcbabagbnmpofaihfiiabaaaaaahialaaaaadaaaaaa
cmaaaaaammaaaaaaaaabaaaaejfdeheojiaaaaaaafaaaaaaaiaaaaaaiaaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaimaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapalaaaaimaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaaimaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaaahaaaaaaimaaaaaa
adaaaaaaaaaaaaaaadaaaaaaaeaaaaaaahahaaaafdfgfpfaepfdejfeejepeoaa
feeffiedepepfceeaaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaacaaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgfheaaklkl
fdeieffihaakaaaafaaaaaaajmacaaaagkaiaaabfjaaaaaeegiocaaaaaaaaaaa
amaaaaaafjaaaaaeegiocaaaabaaaaaaaiaaaaaafkaaaaadaagabaaaaaaaaaaa
fkaaaaadaagabaaaabaaaaaafkaaaaadaagabaaaacaaaaaafibiaaaeaahabaaa
aaaaaaaaffffaaaafibiaaaeaahabaaaabaaaaaaffffaaaaficiaaaeaahabaaa
acaaaaaaffffaaaagcbaaaadlcbabaaaabaaaaaagcbaaaadhcbabaaaacaaaaaa
gcbaaaadhcbabaaaaeaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaacafaaaaaa
aoaaaaahdcaabaaaaaaaaaaaegbabaaaabaaaaaapgbpbaaaabaaaaaadiaaaaaj
hcaabaaaabaaaaaaegiccaaaaaaaaaaaaeaaaaaafgifcaaaaaaaaaaaagaaaaaa
dcaaaaakhcaabaaaabaaaaaaegacbaaaabaaaaaafgafbaaaaaaaaaaaegiccaaa
aaaaaaaaadaaaaaadiaaaaajhcaabaaaacaaaaaaegiccaaaaaaaaaaaafaaaaaa
agiacaaaaaaaaaaaagaaaaaadcaaaaajhcaabaaaabaaaaaaegacbaaaacaaaaaa
agaabaaaaaaaaaaaegacbaaaabaaaaaaaaaaaaaihcaabaaaacaaaaaaegacbaia
ebaaaaaaabaaaaaaegbcbaaaacaaaaaabaaaaaahecaabaaaaaaaaaaaegacbaaa
acaaaaaaegacbaaaacaaaaaaeeaaaaafecaabaaaaaaaaaaackaabaaaaaaaaaaa
diaaaaahhcaabaaaacaaaaaakgakbaaaaaaaaaaaegacbaaaacaaaaaaefaaaail
mcaaaaiaedffbfaaecaabaaaaaaaaaaaegaabaaaaaaaaaaajghmbaaaaaaaaaaa
aagabaaaabaaaaaaefaaaailmcaaaaiaedffbfaalcaabaaaaaaaaaaaegaabaaa
aaaaaaaaeghlbaaaabaaaaaaaagabaaaacaaaaaadcaaaaalecaabaaaaaaaaaaa
ckiacaaaabaaaaaaahaaaaaackaabaaaaaaaaaaadkiacaaaabaaaaaaahaaaaaa
aoaaaaakecaabaaaaaaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaiadp
ckaabaaaaaaaaaaaaaaaaaajicaabaaaabaaaaaaakiacaaaaaaaaaaaajaaaaaa
akiacaaaaaaaaaaaajaaaaaadgaaaaafhcaabaaaadaaaaaaegacbaaaabaaaaaa
dgaaaaaficaabaaaacaaaaaaabeaaaaaaaaaaaaadgaaaaaficaabaaaadaaaaaa
abeaaaaaaaaaaaaadaaaaaabcbaaaaahbcaabaaaaeaaaaaadkaabaaaadaaaaaa
abeaaaaaaaabaaaaadaaaeadakaabaaaaeaaaaaaaaaaaaajhcaabaaaaeaaaaaa
egacbaiaebaaaaaaadaaaaaaegiccaaaabaaaaaaaeaaaaaabaaaaaahbcaabaaa
aeaaaaaaegacbaaaaeaaaaaaegacbaaaaeaaaaaaelaaaaafbcaabaaaaeaaaaaa
akaabaaaaeaaaaaabnaaaaahbcaabaaaaeaaaaaaakaabaaaaeaaaaaackaabaaa
aaaaaaaabpaaaeadakaabaaaaeaaaaaaacaaaaabbfaaaaabaaaaaaajhcaabaaa
aeaaaaaaegacbaaaadaaaaaaegiccaiaebaaaaaaaaaaaaaaaiaaaaaaaaaaaaai
hcaabaaaaeaaaaaaegacbaaaaeaaaaaaagiacaaaaaaaaaaaajaaaaaaaoaaaaah
hcaabaaaaeaaaaaaegacbaaaaeaaaaaapgapbaaaabaaaaaaeiaaaainecabaaia
edffbfaabcaabaaaaeaaaaaaegacbaaaaeaaaaaaeghobaaaacaaaaaaaagabaaa
aaaaaaaaabeaaaaaaaaaaaaadjaaaaahccaabaaaaeaaaaaaakaabaaaaeaaaaaa
abeaaaaaaaaaaaaacpaaaaagbcaabaaaaeaaaaaaakaabaiaibaaaaaaaeaaaaaa
diaaaaahbcaabaaaaeaaaaaaakaabaaaaeaaaaaaabeaaaaajlcajkdoaaaaaaai
bcaabaaaaeaaaaaaakaabaiambaaaaaaaeaaaaaaabeaaaaaaaaaiadpabaaaaah
bcaabaaaaeaaaaaaakaabaaaaeaaaaaabkaabaaaaeaaaaaadiaaaaaibcaabaaa
aeaaaaaaakaabaaaaeaaaaaabkiacaaaaaaaaaaaajaaaaaaaaaaaaaiccaabaaa
aeaaaaaadkaabaiaebaaaaaaacaaaaaaabeaaaaaaaaaiadpdcaaaaajicaabaaa
acaaaaaabkaabaaaaeaaaaaaakaabaaaaeaaaaaadkaabaaaacaaaaaadcaaaaak
hcaabaaaadaaaaaaegacbaaaacaaaaaaagiacaaaaaaaaaaaahaaaaaaegacbaaa
adaaaaaaboaaaaahicaabaaaadaaaaaadkaabaaaadaaaaaaabeaaaaaabaaaaaa
bgaaaaabaaaaaaaiecaabaaaaaaaaaaadkaabaiaebaaaaaaacaaaaaaabeaaaaa
aaaaiadpdiaaaaaihcaabaaaabaaaaaakgakbaaaaaaaaaaaegiccaaaaaaaaaaa
akaaaaaadeaaaaahecaabaaaaaaaaaaadkaabaaaaaaaaaaabkaabaaaaaaaaaaa
deaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaaakaabaaaaaaaaaaaddaaaaah
icaabaaaabaaaaaadkaabaaaaaaaaaaabkaabaaaaaaaaaaaddaaaaahicaabaaa
abaaaaaaakaabaaaaaaaaaaadkaabaaaabaaaaaaaaaaaaaiicaabaaaabaaaaaa
ckaabaaaaaaaaaaadkaabaiaebaaaaaaabaaaaaadjaaaaahbcaabaaaacaaaaaa
dkaabaaaabaaaaaaabeaaaaaaaaaaaaaaaaaaaaiocaabaaaacaaaaaaaganbaia
ebaaaaaaaaaaaaaakgakbaaaaaaaaaaaaoaaaaahocaabaaaacaaaaaafgaobaaa
acaaaaaapgapbaaaabaaaaaaaaaaaaaiocaabaaaacaaaaaapgajbaiaebaaaaaa
acaaaaaafgaobaaaacaaaaaaaaaaaaakgcaabaaaacaaaaaafgagbaaaacaaaaaa
aceaaaaaaaaaaaaaaaaaaaeaaaaaiaeaaaaaaaaabnaaaaahdcaabaaaaaaaaaaa
egaabaaaaaaaaaaakgakbaaaaaaaaaaadhaaaaajccaabaaaaaaaaaaabkaabaaa
aaaaaaaabkaabaaaacaaaaaackaabaaaacaaaaaadhaaaaajbcaabaaaaaaaaaaa
akaabaaaaaaaaaaadkaabaaaacaaaaaabkaabaaaaaaaaaaadiaaaaahbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaabeaaaaaklkkckdobkaaaaafbcaabaaaaaaaaaaa
akaabaaaaaaaaaaaabaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaakaabaaa
acaaaaaadeaaaaahccaabaaaaaaaaaaackaabaaaabaaaaaabkaabaaaabaaaaaa
deaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaabaaaaaaddaaaaah
ecaabaaaaaaaaaaackaabaaaabaaaaaabkaabaaaabaaaaaaddaaaaahecaabaaa
aaaaaaaackaabaaaaaaaaaaaakaabaaaabaaaaaaaaaaaaaiecaabaaaaaaaaaaa
ckaabaiaebaaaaaaaaaaaaaabkaabaaaaaaaaaaadjaaaaahicaabaaaaaaaaaaa
ckaabaaaaaaaaaaaabeaaaaaaaaaaaaaaoaaaaahecaabaaaaaaaaaaackaabaaa
aaaaaaaabkaabaaaaaaaaaaaabaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaa
dkaabaaaaaaaaaaadcaaaaaphcaabaaaacaaaaaaagaabaaaaaaaaaaaaceaaaaa
aaaamaeaaaaamaeaaaaamaeaaaaaaaaaaceaaaaaaaaaeamaaaaaaamaaaaaiama
aaaaaaaadccaaabahcaabaaaacaaaaaaegacbaiaibaaaaaaacaaaaaaaceaaaaa
aaaaiadpaaaaialpaaaaialpaaaaaaaaaceaaaaaaaaaialpaaaaaaeaaaaaaaea
aaaaaaaaaaaaaaakhcaabaaaacaaaaaaegacbaaaacaaaaaaaceaaaaaaaaaialp
aaaaialpaaaaialpaaaaaaaadcaaaaamncaabaaaaaaaaaaaagajbaaaacaaaaaa
kgakbaaaaaaaaaaaaceaaaaaaaaaiadpaaaaaaaaaaaaiadpaaaaiadpdiaaaaah
ncaabaaaaaaaaaaafgafbaaaaaaaaaaaagaobaaaaaaaaaaaaaaaaaajccaabaaa
aaaaaaaabkaabaaaaaaaaaaaakiacaiaebaaaaaaaaaaaaaaalaaaaaadeaaaaah
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaaaaaaaaaaaakicaabaaa
abaaaaaaakiacaiaebaaaaaaaaaaaaaaalaaaaaabkiacaaaaaaaaaaaalaaaaaa
aoaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaadkaabaaaabaaaaaaaaaaaaai
icaabaaaabaaaaaabkaabaiaebaaaaaaaaaaaaaaabeaaaaaaaaaiadpdiaaaaah
hcaabaaaaaaaaaaaigadbaaaaaaaaaaafgafbaaaaaaaaaaadcaaaaajhcaabaaa
aaaaaaaapgapbaaaabaaaaaaegacbaaaabaaaaaaegacbaaaaaaaaaaadcaaaaaj
hccabaaaaaaaaaaaegacbaaaaaaaaaaaegbcbaaaaeaaaaaaegacbaaaaaaaaaaa
dgaaaaaficcabaaaaaaaaaaaabeaaaaaaaaaiadpdoaaaaab"
}
SubProgram "d3d11 " {
Keywords { "DIRECTIONAL" "LIGHTMAP_ON" "DIRLIGHTMAP_OFF" }
SetTexture 0 [_CameraDepthTexture] 2D 1
SetTexture 1 [_Background] 2D 2
SetTexture 2 [Volume] 3D 0
SetTexture 3 [unity_Lightmap] 2D 3
ConstBuffer "$Globals" 208
Vector 48 [screenCorner]
Vector 64 [cameraUp]
Vector 80 [cameraRight]
Vector 96 [cameraWorldSize]
Float 112 [StepSize]
Vector 128 [worldOrigin]
Float 144 [halfWorldSize]
Float 148 [transparency]
Vector 160 [bored]
Float 176 [minF]
Float 180 [maxF]
ConstBuffer "UnityPerCamera" 128
Vector 64 [_WorldSpaceCameraPos] 3
Vector 112 [_ZBufferParams]
BindCB  "$Globals" 0
BindCB  "UnityPerCamera" 1
"ps_5_0
eefiecedjokaahgmbjhehbmlolcjegimkljbepfaabaaaaaanialaaaaadaaaaaa
cmaaaaaaleaaaaaaoiaaaaaaejfdeheoiaaaaaaaaeaaaaaaaiaaaaaagiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaheaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapalaaaaheaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaaheaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaaadadaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaklklklepfdeheocmaaaaaaabaaaaaa
aiaaaaaacaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaafdfgfpfe
gbhcghgfheaaklklfdeieffioiakaaaafaaaaaaalkacaaaagkaiaaabfjaaaaae
egiocaaaaaaaaaaaamaaaaaafjaaaaaeegiocaaaabaaaaaaaiaaaaaafkaaaaad
aagabaaaaaaaaaaafkaaaaadaagabaaaabaaaaaafkaaaaadaagabaaaacaaaaaa
fkaaaaadaagabaaaadaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaafibiaaae
aahabaaaabaaaaaaffffaaaaficiaaaeaahabaaaacaaaaaaffffaaaafibiaaae
aahabaaaadaaaaaaffffaaaagcbaaaadlcbabaaaabaaaaaagcbaaaadhcbabaaa
acaaaaaagcbaaaaddcbabaaaadaaaaaagfaaaaadpccabaaaaaaaaaaagiaaaaac
afaaaaaaaoaaaaahdcaabaaaaaaaaaaaegbabaaaabaaaaaapgbpbaaaabaaaaaa
diaaaaajhcaabaaaabaaaaaaegiccaaaaaaaaaaaaeaaaaaafgifcaaaaaaaaaaa
agaaaaaadcaaaaakhcaabaaaabaaaaaaegacbaaaabaaaaaafgafbaaaaaaaaaaa
egiccaaaaaaaaaaaadaaaaaadiaaaaajhcaabaaaacaaaaaaegiccaaaaaaaaaaa
afaaaaaaagiacaaaaaaaaaaaagaaaaaadcaaaaajhcaabaaaabaaaaaaegacbaaa
acaaaaaaagaabaaaaaaaaaaaegacbaaaabaaaaaaaaaaaaaihcaabaaaacaaaaaa
egacbaiaebaaaaaaabaaaaaaegbcbaaaacaaaaaabaaaaaahecaabaaaaaaaaaaa
egacbaaaacaaaaaaegacbaaaacaaaaaaeeaaaaafecaabaaaaaaaaaaackaabaaa
aaaaaaaadiaaaaahhcaabaaaacaaaaaakgakbaaaaaaaaaaaegacbaaaacaaaaaa
efaaaailmcaaaaiaedffbfaaecaabaaaaaaaaaaaegaabaaaaaaaaaaajghmbaaa
aaaaaaaaaagabaaaabaaaaaaefaaaailmcaaaaiaedffbfaalcaabaaaaaaaaaaa
egaabaaaaaaaaaaaeghlbaaaabaaaaaaaagabaaaacaaaaaadcaaaaalecaabaaa
aaaaaaaackiacaaaabaaaaaaahaaaaaackaabaaaaaaaaaaadkiacaaaabaaaaaa
ahaaaaaaaoaaaaakecaabaaaaaaaaaaaaceaaaaaaaaaiadpaaaaiadpaaaaiadp
aaaaiadpckaabaaaaaaaaaaaaaaaaaajicaabaaaabaaaaaaakiacaaaaaaaaaaa
ajaaaaaaakiacaaaaaaaaaaaajaaaaaadgaaaaafhcaabaaaadaaaaaaegacbaaa
abaaaaaadgaaaaaficaabaaaacaaaaaaabeaaaaaaaaaaaaadgaaaaaficaabaaa
adaaaaaaabeaaaaaaaaaaaaadaaaaaabcbaaaaahbcaabaaaaeaaaaaadkaabaaa
adaaaaaaabeaaaaaaaabaaaaadaaaeadakaabaaaaeaaaaaaaaaaaaajhcaabaaa
aeaaaaaaegacbaiaebaaaaaaadaaaaaaegiccaaaabaaaaaaaeaaaaaabaaaaaah
bcaabaaaaeaaaaaaegacbaaaaeaaaaaaegacbaaaaeaaaaaaelaaaaafbcaabaaa
aeaaaaaaakaabaaaaeaaaaaabnaaaaahbcaabaaaaeaaaaaaakaabaaaaeaaaaaa
ckaabaaaaaaaaaaabpaaaeadakaabaaaaeaaaaaaacaaaaabbfaaaaabaaaaaaaj
hcaabaaaaeaaaaaaegacbaaaadaaaaaaegiccaiaebaaaaaaaaaaaaaaaiaaaaaa
aaaaaaaihcaabaaaaeaaaaaaegacbaaaaeaaaaaaagiacaaaaaaaaaaaajaaaaaa
aoaaaaahhcaabaaaaeaaaaaaegacbaaaaeaaaaaapgapbaaaabaaaaaaeiaaaain
ecabaaiaedffbfaabcaabaaaaeaaaaaaegacbaaaaeaaaaaaeghobaaaacaaaaaa
aagabaaaaaaaaaaaabeaaaaaaaaaaaaadjaaaaahccaabaaaaeaaaaaaakaabaaa
aeaaaaaaabeaaaaaaaaaaaaacpaaaaagbcaabaaaaeaaaaaaakaabaiaibaaaaaa
aeaaaaaadiaaaaahbcaabaaaaeaaaaaaakaabaaaaeaaaaaaabeaaaaajlcajkdo
aaaaaaaibcaabaaaaeaaaaaaakaabaiambaaaaaaaeaaaaaaabeaaaaaaaaaiadp
abaaaaahbcaabaaaaeaaaaaaakaabaaaaeaaaaaabkaabaaaaeaaaaaadiaaaaai
bcaabaaaaeaaaaaaakaabaaaaeaaaaaabkiacaaaaaaaaaaaajaaaaaaaaaaaaai
ccaabaaaaeaaaaaadkaabaiaebaaaaaaacaaaaaaabeaaaaaaaaaiadpdcaaaaaj
icaabaaaacaaaaaabkaabaaaaeaaaaaaakaabaaaaeaaaaaadkaabaaaacaaaaaa
dcaaaaakhcaabaaaadaaaaaaegacbaaaacaaaaaaagiacaaaaaaaaaaaahaaaaaa
egacbaaaadaaaaaaboaaaaahicaabaaaadaaaaaadkaabaaaadaaaaaaabeaaaaa
abaaaaaabgaaaaabaaaaaaaiecaabaaaaaaaaaaadkaabaiaebaaaaaaacaaaaaa
abeaaaaaaaaaiadpdiaaaaaihcaabaaaabaaaaaakgakbaaaaaaaaaaaegiccaaa
aaaaaaaaakaaaaaadeaaaaahecaabaaaaaaaaaaadkaabaaaaaaaaaaabkaabaaa
aaaaaaaadeaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaaakaabaaaaaaaaaaa
ddaaaaahicaabaaaabaaaaaadkaabaaaaaaaaaaabkaabaaaaaaaaaaaddaaaaah
icaabaaaabaaaaaaakaabaaaaaaaaaaadkaabaaaabaaaaaaaaaaaaaiicaabaaa
abaaaaaackaabaaaaaaaaaaadkaabaiaebaaaaaaabaaaaaadjaaaaahbcaabaaa
acaaaaaadkaabaaaabaaaaaaabeaaaaaaaaaaaaaaaaaaaaiocaabaaaacaaaaaa
aganbaiaebaaaaaaaaaaaaaakgakbaaaaaaaaaaaaoaaaaahocaabaaaacaaaaaa
fgaobaaaacaaaaaapgapbaaaabaaaaaaaaaaaaaiocaabaaaacaaaaaapgajbaia
ebaaaaaaacaaaaaafgaobaaaacaaaaaaaaaaaaakgcaabaaaacaaaaaafgagbaaa
acaaaaaaaceaaaaaaaaaaaaaaaaaaaeaaaaaiaeaaaaaaaaabnaaaaahdcaabaaa
aaaaaaaaegaabaaaaaaaaaaakgakbaaaaaaaaaaadhaaaaajccaabaaaaaaaaaaa
bkaabaaaaaaaaaaabkaabaaaacaaaaaackaabaaaacaaaaaadhaaaaajbcaabaaa
aaaaaaaaakaabaaaaaaaaaaadkaabaaaacaaaaaabkaabaaaaaaaaaaadiaaaaah
bcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaklkkckdobkaaaaafbcaabaaa
aaaaaaaaakaabaaaaaaaaaaaabaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
akaabaaaacaaaaaadeaaaaahccaabaaaaaaaaaaackaabaaaabaaaaaabkaabaaa
abaaaaaadeaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaakaabaaaabaaaaaa
ddaaaaahecaabaaaaaaaaaaackaabaaaabaaaaaabkaabaaaabaaaaaaddaaaaah
ecaabaaaaaaaaaaackaabaaaaaaaaaaaakaabaaaabaaaaaaaaaaaaaiecaabaaa
aaaaaaaackaabaiaebaaaaaaaaaaaaaabkaabaaaaaaaaaaadjaaaaahicaabaaa
aaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaaaaaaoaaaaahecaabaaaaaaaaaaa
ckaabaaaaaaaaaaabkaabaaaaaaaaaaaabaaaaahecaabaaaaaaaaaaackaabaaa
aaaaaaaadkaabaaaaaaaaaaadcaaaaaphcaabaaaacaaaaaaagaabaaaaaaaaaaa
aceaaaaaaaaamaeaaaaamaeaaaaamaeaaaaaaaaaaceaaaaaaaaaeamaaaaaaama
aaaaiamaaaaaaaaadccaaabahcaabaaaacaaaaaaegacbaiaibaaaaaaacaaaaaa
aceaaaaaaaaaiadpaaaaialpaaaaialpaaaaaaaaaceaaaaaaaaaialpaaaaaaea
aaaaaaeaaaaaaaaaaaaaaaakhcaabaaaacaaaaaaegacbaaaacaaaaaaaceaaaaa
aaaaialpaaaaialpaaaaialpaaaaaaaadcaaaaamncaabaaaaaaaaaaaagajbaaa
acaaaaaakgakbaaaaaaaaaaaaceaaaaaaaaaiadpaaaaaaaaaaaaiadpaaaaiadp
diaaaaahncaabaaaaaaaaaaafgafbaaaaaaaaaaaagaobaaaaaaaaaaaaaaaaaaj
ccaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaiaebaaaaaaaaaaaaaaalaaaaaa
deaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaaaaaaaaaaaaaaaaak
icaabaaaabaaaaaaakiacaiaebaaaaaaaaaaaaaaalaaaaaabkiacaaaaaaaaaaa
alaaaaaaaoaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaadkaabaaaabaaaaaa
aaaaaaaiicaabaaaabaaaaaabkaabaiaebaaaaaaaaaaaaaaabeaaaaaaaaaiadp
diaaaaahhcaabaaaaaaaaaaaigadbaaaaaaaaaaafgafbaaaaaaaaaaadcaaaaaj
hcaabaaaaaaaaaaapgapbaaaabaaaaaaegacbaaaabaaaaaaegacbaaaaaaaaaaa
efaaaailmcaaaaiaedffbfaapcaabaaaabaaaaaaegbabaaaadaaaaaaeghobaaa
adaaaaaaaagabaaaadaaaaaadiaaaaahicaabaaaaaaaaaaadkaabaaaabaaaaaa
abeaaaaaaaaaaaebdiaaaaahhcaabaaaabaaaaaaegacbaaaabaaaaaapgapbaaa
aaaaaaaadiaaaaahhccabaaaaaaaaaaaegacbaaaaaaaaaaaegacbaaaabaaaaaa
dgaaaaaficcabaaaaaaaaaaaabeaaaaaaaaaiadpdoaaaaab"
}
}
 }
 Pass {
  Name "FORWARD"
  Tags { "LIGHTMODE"="ForwardAdd" }
  ZTest Always
  ZWrite Off
  Cull Front
  Fog {
   Color (0,0,0,0)
  }
  Blend SrcAlpha One
  AlphaTest Greater 0
  ColorMask RGB
Program "vp" {
SubProgram "d3d11 " {
Keywords { "POINT" }
Bind "vertex" Vertex
Bind "color" Color
Bind "normal" Normal
ConstBuffer "$Globals" 256
Matrix 48 [_LightMatrix0]
ConstBuffer "UnityPerCamera" 128
Vector 80 [_ProjectionParams]
ConstBuffer "UnityLighting" 400
Vector 0 [_WorldSpaceLightPos0]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
Matrix 192 [_Object2World]
Vector 320 [unity_Scale]
BindCB  "$Globals" 0
BindCB  "UnityPerCamera" 1
BindCB  "UnityLighting" 2
BindCB  "UnityPerDraw" 3
"vs_5_0
eefiecedbfambjojncijnbcfhnbbhimojjnlpjbcabaaaaaaceagaaaaadaaaaaa
cmaaaaaapeaaaaaakmabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapaaaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapaaaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheolaaaaaaaagaaaaaa
aiaaaaaajiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaakeaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaapaaaaaakeaaaaaaabaaaaaaaaaaaaaa
adaaaaaaacaaaaaaahaiaaaakeaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaa
ahaiaaaakeaaaaaaadaaaaaaaaaaaaaaadaaaaaaaeaaaaaaahaiaaaakeaaaaaa
aeaaaaaaaaaaaaaaadaaaaaaafaaaaaaahaiaaaafdfgfpfaepfdejfeejepeoaa
feeffiedepepfceeaaklklklfdeieffihaaeaaaafaaaabaabmabaaaagkaiaaab
fjaaaaaeegiocaaaaaaaaaaaahaaaaaafjaaaaaeegiocaaaabaaaaaaagaaaaaa
fjaaaaaeegiocaaaacaaaaaaabaaaaaafjaaaaaeegiocaaaadaaaaaabfaaaaaa
fpaaaaadpcbabaaaaaaaaaaafpaaaaadhcbabaaaacaaaaaaghaaaaaepccabaaa
aaaaaaaaabaaaaaagfaaaaadpccabaaaabaaaaaagfaaaaadhccabaaaacaaaaaa
gfaaaaadhccabaaaadaaaaaagfaaaaadhccabaaaaeaaaaaagfaaaaadhccabaaa
afaaaaaagiaaaaacacaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaa
egiocaaaadaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaadaaaaaa
aaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaa
egiocaaaadaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaak
pcaabaaaaaaaaaaaegiocaaaadaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaa
aaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaaiccaabaaa
aaaaaaaabkaabaaaaaaaaaaaakiacaaaabaaaaaaafaaaaaadiaaaaakncaabaaa
abaaaaaaagahbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaaaaaaaaaadpaaaaaadp
dgaaaaafmccabaaaabaaaaaakgaobaaaaaaaaaaaaaaaaaahdccabaaaabaaaaaa
kgakbaaaabaaaaaamgaabaaaabaaaaaadiaaaaaihcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiccaaaadaaaaaaanaaaaaadcaaaaakhcaabaaaaaaaaaaaegiccaaa
adaaaaaaamaaaaaaagbabaaaaaaaaaaaegacbaaaaaaaaaaadcaaaaakhcaabaaa
aaaaaaaaegiccaaaadaaaaaaaoaaaaaakgbkbaaaaaaaaaaaegacbaaaaaaaaaaa
dcaaaaakhcaabaaaaaaaaaaaegiccaaaadaaaaaaapaaaaaapgbpbaaaaaaaaaaa
egacbaaaaaaaaaaadgaaaaafhccabaaaacaaaaaaegacbaaaaaaaaaaaaaaaaaaj
hccabaaaaeaaaaaaegacbaiaebaaaaaaaaaaaaaaegiccaaaacaaaaaaaaaaaaaa
diaaaaaihcaabaaaaaaaaaaaegbcbaaaacaaaaaapgipcaaaadaaaaaabeaaaaaa
diaaaaaihcaabaaaabaaaaaafgafbaaaaaaaaaaaegiccaaaadaaaaaaanaaaaaa
dcaaaaaklcaabaaaaaaaaaaaegiicaaaadaaaaaaamaaaaaaagaabaaaaaaaaaaa
egaibaaaabaaaaaadcaaaaakhccabaaaadaaaaaaegiccaaaadaaaaaaaoaaaaaa
kgakbaaaaaaaaaaaegadbaaaaaaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaadaaaaaaanaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
adaaaaaaamaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaadaaaaaaaoaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaadaaaaaaapaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadiaaaaaihcaabaaaabaaaaaafgafbaaaaaaaaaaaegiccaaa
aaaaaaaaaeaaaaaadcaaaaakhcaabaaaabaaaaaaegiccaaaaaaaaaaaadaaaaaa
agaabaaaaaaaaaaaegacbaaaabaaaaaadcaaaaakhcaabaaaaaaaaaaaegiccaaa
aaaaaaaaafaaaaaakgakbaaaaaaaaaaaegacbaaaabaaaaaadcaaaaakhccabaaa
afaaaaaaegiccaaaaaaaaaaaagaaaaaapgapbaaaaaaaaaaaegacbaaaaaaaaaaa
doaaaaab"
}
SubProgram "d3d11 " {
Keywords { "DIRECTIONAL" }
Bind "vertex" Vertex
Bind "color" Color
Bind "normal" Normal
ConstBuffer "UnityPerCamera" 128
Vector 80 [_ProjectionParams]
ConstBuffer "UnityLighting" 400
Vector 0 [_WorldSpaceLightPos0]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
Matrix 192 [_Object2World]
Vector 320 [unity_Scale]
BindCB  "UnityPerCamera" 0
BindCB  "UnityLighting" 1
BindCB  "UnityPerDraw" 2
"vs_5_0
eefiecedepbpnhbehglpojocbpnglkifjjgekaffabaaaaaakaaeaaaaadaaaaaa
cmaaaaaapeaaaaaajeabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapaaaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapaaaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheojiaaaaaaafaaaaaa
aiaaaaaaiaaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaimaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaapaaaaaaimaaaaaaabaaaaaaaaaaaaaa
adaaaaaaacaaaaaaahaiaaaaimaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaa
ahaiaaaaimaaaaaaadaaaaaaaaaaaaaaadaaaaaaaeaaaaaaahaiaaaafdfgfpfa
epfdejfeejepeoaafeeffiedepepfceeaaklklklfdeieffiaeadaaaafaaaabaa
mbaaaaaagkaiaaabfjaaaaaeegiocaaaaaaaaaaaagaaaaaafjaaaaaeegiocaaa
abaaaaaaabaaaaaafjaaaaaeegiocaaaacaaaaaabfaaaaaafpaaaaadpcbabaaa
aaaaaaaafpaaaaadhcbabaaaacaaaaaaghaaaaaepccabaaaaaaaaaaaabaaaaaa
gfaaaaadpccabaaaabaaaaaagfaaaaadhccabaaaacaaaaaagfaaaaadhccabaaa
adaaaaaagfaaaaadhccabaaaaeaaaaaagiaaaaacacaaaaaadiaaaaaipcaabaaa
aaaaaaaafgbfbaaaaaaaaaaaegiocaaaacaaaaaaabaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaacaaaaaaaaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaacaaaaaaacaaaaaakgbkbaaaaaaaaaaa
egaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaacaaaaaaadaaaaaa
pgbpbaaaaaaaaaaaegaobaaaaaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaa
aaaaaaaadiaaaaaiccaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaaaaaaaaaaa
afaaaaaadiaaaaakncaabaaaabaaaaaaagahbaaaaaaaaaaaaceaaaaaaaaaaadp
aaaaaaaaaaaaaadpaaaaaadpdgaaaaafmccabaaaabaaaaaakgaobaaaaaaaaaaa
aaaaaaahdccabaaaabaaaaaakgakbaaaabaaaaaamgaabaaaabaaaaaadiaaaaai
hcaabaaaaaaaaaaafgbfbaaaaaaaaaaaegiccaaaacaaaaaaanaaaaaadcaaaaak
hcaabaaaaaaaaaaaegiccaaaacaaaaaaamaaaaaaagbabaaaaaaaaaaaegacbaaa
aaaaaaaadcaaaaakhcaabaaaaaaaaaaaegiccaaaacaaaaaaaoaaaaaakgbkbaaa
aaaaaaaaegacbaaaaaaaaaaadcaaaaakhccabaaaacaaaaaaegiccaaaacaaaaaa
apaaaaaapgbpbaaaaaaaaaaaegacbaaaaaaaaaaadiaaaaaihcaabaaaaaaaaaaa
egbcbaaaacaaaaaapgipcaaaacaaaaaabeaaaaaadiaaaaaihcaabaaaabaaaaaa
fgafbaaaaaaaaaaaegiccaaaacaaaaaaanaaaaaadcaaaaaklcaabaaaaaaaaaaa
egiicaaaacaaaaaaamaaaaaaagaabaaaaaaaaaaaegaibaaaabaaaaaadcaaaaak
hccabaaaadaaaaaaegiccaaaacaaaaaaaoaaaaaakgakbaaaaaaaaaaaegadbaaa
aaaaaaaadgaaaaaghccabaaaaeaaaaaaegiccaaaabaaaaaaaaaaaaaadoaaaaab
"
}
SubProgram "d3d11 " {
Keywords { "SPOT" }
Bind "vertex" Vertex
Bind "color" Color
Bind "normal" Normal
ConstBuffer "$Globals" 256
Matrix 48 [_LightMatrix0]
ConstBuffer "UnityPerCamera" 128
Vector 80 [_ProjectionParams]
ConstBuffer "UnityLighting" 400
Vector 0 [_WorldSpaceLightPos0]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
Matrix 192 [_Object2World]
Vector 320 [unity_Scale]
BindCB  "$Globals" 0
BindCB  "UnityPerCamera" 1
BindCB  "UnityLighting" 2
BindCB  "UnityPerDraw" 3
"vs_5_0
eefiecedijepnjficgbpkapiahaiohemaapgghjhabaaaaaaceagaaaaadaaaaaa
cmaaaaaapeaaaaaakmabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapaaaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapaaaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheolaaaaaaaagaaaaaa
aiaaaaaajiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaakeaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaapaaaaaakeaaaaaaabaaaaaaaaaaaaaa
adaaaaaaacaaaaaaahaiaaaakeaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaa
ahaiaaaakeaaaaaaadaaaaaaaaaaaaaaadaaaaaaaeaaaaaaahaiaaaakeaaaaaa
aeaaaaaaaaaaaaaaadaaaaaaafaaaaaaapaaaaaafdfgfpfaepfdejfeejepeoaa
feeffiedepepfceeaaklklklfdeieffihaaeaaaafaaaabaabmabaaaagkaiaaab
fjaaaaaeegiocaaaaaaaaaaaahaaaaaafjaaaaaeegiocaaaabaaaaaaagaaaaaa
fjaaaaaeegiocaaaacaaaaaaabaaaaaafjaaaaaeegiocaaaadaaaaaabfaaaaaa
fpaaaaadpcbabaaaaaaaaaaafpaaaaadhcbabaaaacaaaaaaghaaaaaepccabaaa
aaaaaaaaabaaaaaagfaaaaadpccabaaaabaaaaaagfaaaaadhccabaaaacaaaaaa
gfaaaaadhccabaaaadaaaaaagfaaaaadhccabaaaaeaaaaaagfaaaaadpccabaaa
afaaaaaagiaaaaacacaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaa
egiocaaaadaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaadaaaaaa
aaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaa
egiocaaaadaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaak
pcaabaaaaaaaaaaaegiocaaaadaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaa
aaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaaiccaabaaa
aaaaaaaabkaabaaaaaaaaaaaakiacaaaabaaaaaaafaaaaaadiaaaaakncaabaaa
abaaaaaaagahbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaaaaaaaaaadpaaaaaadp
dgaaaaafmccabaaaabaaaaaakgaobaaaaaaaaaaaaaaaaaahdccabaaaabaaaaaa
kgakbaaaabaaaaaamgaabaaaabaaaaaadiaaaaaihcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiccaaaadaaaaaaanaaaaaadcaaaaakhcaabaaaaaaaaaaaegiccaaa
adaaaaaaamaaaaaaagbabaaaaaaaaaaaegacbaaaaaaaaaaadcaaaaakhcaabaaa
aaaaaaaaegiccaaaadaaaaaaaoaaaaaakgbkbaaaaaaaaaaaegacbaaaaaaaaaaa
dcaaaaakhcaabaaaaaaaaaaaegiccaaaadaaaaaaapaaaaaapgbpbaaaaaaaaaaa
egacbaaaaaaaaaaadgaaaaafhccabaaaacaaaaaaegacbaaaaaaaaaaaaaaaaaaj
hccabaaaaeaaaaaaegacbaiaebaaaaaaaaaaaaaaegiccaaaacaaaaaaaaaaaaaa
diaaaaaihcaabaaaaaaaaaaaegbcbaaaacaaaaaapgipcaaaadaaaaaabeaaaaaa
diaaaaaihcaabaaaabaaaaaafgafbaaaaaaaaaaaegiccaaaadaaaaaaanaaaaaa
dcaaaaaklcaabaaaaaaaaaaaegiicaaaadaaaaaaamaaaaaaagaabaaaaaaaaaaa
egaibaaaabaaaaaadcaaaaakhccabaaaadaaaaaaegiccaaaadaaaaaaaoaaaaaa
kgakbaaaaaaaaaaaegadbaaaaaaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaadaaaaaaanaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
adaaaaaaamaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaadaaaaaaaoaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaadaaaaaaapaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadiaaaaaipcaabaaaabaaaaaafgafbaaaaaaaaaaaegiocaaa
aaaaaaaaaeaaaaaadcaaaaakpcaabaaaabaaaaaaegiocaaaaaaaaaaaadaaaaaa
agaabaaaaaaaaaaaegaobaaaabaaaaaadcaaaaakpcaabaaaabaaaaaaegiocaaa
aaaaaaaaafaaaaaakgakbaaaaaaaaaaaegaobaaaabaaaaaadcaaaaakpccabaaa
afaaaaaaegiocaaaaaaaaaaaagaaaaaapgapbaaaaaaaaaaaegaobaaaabaaaaaa
doaaaaab"
}
SubProgram "d3d11 " {
Keywords { "POINT_COOKIE" }
Bind "vertex" Vertex
Bind "color" Color
Bind "normal" Normal
ConstBuffer "$Globals" 256
Matrix 48 [_LightMatrix0]
ConstBuffer "UnityPerCamera" 128
Vector 80 [_ProjectionParams]
ConstBuffer "UnityLighting" 400
Vector 0 [_WorldSpaceLightPos0]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
Matrix 192 [_Object2World]
Vector 320 [unity_Scale]
BindCB  "$Globals" 0
BindCB  "UnityPerCamera" 1
BindCB  "UnityLighting" 2
BindCB  "UnityPerDraw" 3
"vs_5_0
eefiecedbfambjojncijnbcfhnbbhimojjnlpjbcabaaaaaaceagaaaaadaaaaaa
cmaaaaaapeaaaaaakmabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapaaaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapaaaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheolaaaaaaaagaaaaaa
aiaaaaaajiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaakeaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaapaaaaaakeaaaaaaabaaaaaaaaaaaaaa
adaaaaaaacaaaaaaahaiaaaakeaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaa
ahaiaaaakeaaaaaaadaaaaaaaaaaaaaaadaaaaaaaeaaaaaaahaiaaaakeaaaaaa
aeaaaaaaaaaaaaaaadaaaaaaafaaaaaaahaiaaaafdfgfpfaepfdejfeejepeoaa
feeffiedepepfceeaaklklklfdeieffihaaeaaaafaaaabaabmabaaaagkaiaaab
fjaaaaaeegiocaaaaaaaaaaaahaaaaaafjaaaaaeegiocaaaabaaaaaaagaaaaaa
fjaaaaaeegiocaaaacaaaaaaabaaaaaafjaaaaaeegiocaaaadaaaaaabfaaaaaa
fpaaaaadpcbabaaaaaaaaaaafpaaaaadhcbabaaaacaaaaaaghaaaaaepccabaaa
aaaaaaaaabaaaaaagfaaaaadpccabaaaabaaaaaagfaaaaadhccabaaaacaaaaaa
gfaaaaadhccabaaaadaaaaaagfaaaaadhccabaaaaeaaaaaagfaaaaadhccabaaa
afaaaaaagiaaaaacacaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaa
egiocaaaadaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaadaaaaaa
aaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaa
egiocaaaadaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaak
pcaabaaaaaaaaaaaegiocaaaadaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaa
aaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaaiccaabaaa
aaaaaaaabkaabaaaaaaaaaaaakiacaaaabaaaaaaafaaaaaadiaaaaakncaabaaa
abaaaaaaagahbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaaaaaaaaaadpaaaaaadp
dgaaaaafmccabaaaabaaaaaakgaobaaaaaaaaaaaaaaaaaahdccabaaaabaaaaaa
kgakbaaaabaaaaaamgaabaaaabaaaaaadiaaaaaihcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiccaaaadaaaaaaanaaaaaadcaaaaakhcaabaaaaaaaaaaaegiccaaa
adaaaaaaamaaaaaaagbabaaaaaaaaaaaegacbaaaaaaaaaaadcaaaaakhcaabaaa
aaaaaaaaegiccaaaadaaaaaaaoaaaaaakgbkbaaaaaaaaaaaegacbaaaaaaaaaaa
dcaaaaakhcaabaaaaaaaaaaaegiccaaaadaaaaaaapaaaaaapgbpbaaaaaaaaaaa
egacbaaaaaaaaaaadgaaaaafhccabaaaacaaaaaaegacbaaaaaaaaaaaaaaaaaaj
hccabaaaaeaaaaaaegacbaiaebaaaaaaaaaaaaaaegiccaaaacaaaaaaaaaaaaaa
diaaaaaihcaabaaaaaaaaaaaegbcbaaaacaaaaaapgipcaaaadaaaaaabeaaaaaa
diaaaaaihcaabaaaabaaaaaafgafbaaaaaaaaaaaegiccaaaadaaaaaaanaaaaaa
dcaaaaaklcaabaaaaaaaaaaaegiicaaaadaaaaaaamaaaaaaagaabaaaaaaaaaaa
egaibaaaabaaaaaadcaaaaakhccabaaaadaaaaaaegiccaaaadaaaaaaaoaaaaaa
kgakbaaaaaaaaaaaegadbaaaaaaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaadaaaaaaanaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
adaaaaaaamaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaadaaaaaaaoaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaadaaaaaaapaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadiaaaaaihcaabaaaabaaaaaafgafbaaaaaaaaaaaegiccaaa
aaaaaaaaaeaaaaaadcaaaaakhcaabaaaabaaaaaaegiccaaaaaaaaaaaadaaaaaa
agaabaaaaaaaaaaaegacbaaaabaaaaaadcaaaaakhcaabaaaaaaaaaaaegiccaaa
aaaaaaaaafaaaaaakgakbaaaaaaaaaaaegacbaaaabaaaaaadcaaaaakhccabaaa
afaaaaaaegiccaaaaaaaaaaaagaaaaaapgapbaaaaaaaaaaaegacbaaaaaaaaaaa
doaaaaab"
}
SubProgram "d3d11 " {
Keywords { "DIRECTIONAL_COOKIE" }
Bind "vertex" Vertex
Bind "color" Color
Bind "normal" Normal
ConstBuffer "$Globals" 256
Matrix 48 [_LightMatrix0]
ConstBuffer "UnityPerCamera" 128
Vector 80 [_ProjectionParams]
ConstBuffer "UnityLighting" 400
Vector 0 [_WorldSpaceLightPos0]
ConstBuffer "UnityPerDraw" 336
Matrix 0 [glstate_matrix_mvp]
Matrix 192 [_Object2World]
Vector 320 [unity_Scale]
BindCB  "$Globals" 0
BindCB  "UnityPerCamera" 1
BindCB  "UnityLighting" 2
BindCB  "UnityPerDraw" 3
"vs_5_0
eefiecedgniefeijblelpgkcakhkgmhanbcclnmeabaaaaaaaeagaaaaadaaaaaa
cmaaaaaapeaaaaaakmabaaaaejfdeheomaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapapaaaakbaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapaaaaaakjaaaaaaaaaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaalaaaaaaaaaaaaaaaaaaaaaaaadaaaaaaadaaaaaaapaaaaaalaaaaaaa
abaaaaaaaaaaaaaaadaaaaaaaeaaaaaaapaaaaaaljaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapaaaaaafaepfdejfeejepeoaafeebeoehefeofeaaeoepfc
enebemaafeeffiedepepfceeaaedepemepfcaaklepfdeheolaaaaaaaagaaaaaa
aiaaaaaajiaaaaaaaaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaakeaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaabaaaaaaapaaaaaakeaaaaaaabaaaaaaaaaaaaaa
adaaaaaaacaaaaaaahaiaaaakeaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaa
ahaiaaaakeaaaaaaadaaaaaaaaaaaaaaadaaaaaaaeaaaaaaahaiaaaakeaaaaaa
aeaaaaaaaaaaaaaaadaaaaaaafaaaaaaadamaaaafdfgfpfaepfdejfeejepeoaa
feeffiedepepfceeaaklklklfdeieffifaaeaaaafaaaabaabeabaaaagkaiaaab
fjaaaaaeegiocaaaaaaaaaaaahaaaaaafjaaaaaeegiocaaaabaaaaaaagaaaaaa
fjaaaaaeegiocaaaacaaaaaaabaaaaaafjaaaaaeegiocaaaadaaaaaabfaaaaaa
fpaaaaadpcbabaaaaaaaaaaafpaaaaadhcbabaaaacaaaaaaghaaaaaepccabaaa
aaaaaaaaabaaaaaagfaaaaadpccabaaaabaaaaaagfaaaaadhccabaaaacaaaaaa
gfaaaaadhccabaaaadaaaaaagfaaaaadhccabaaaaeaaaaaagfaaaaaddccabaaa
afaaaaaagiaaaaacacaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaaaaaaaaaa
egiocaaaadaaaaaaabaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaaadaaaaaa
aaaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaaaaaaaaaa
egiocaaaadaaaaaaacaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaak
pcaabaaaaaaaaaaaegiocaaaadaaaaaaadaaaaaapgbpbaaaaaaaaaaaegaobaaa
aaaaaaaadgaaaaafpccabaaaaaaaaaaaegaobaaaaaaaaaaadiaaaaaiccaabaaa
aaaaaaaabkaabaaaaaaaaaaaakiacaaaabaaaaaaafaaaaaadiaaaaakncaabaaa
abaaaaaaagahbaaaaaaaaaaaaceaaaaaaaaaaadpaaaaaaaaaaaaaadpaaaaaadp
dgaaaaafmccabaaaabaaaaaakgaobaaaaaaaaaaaaaaaaaahdccabaaaabaaaaaa
kgakbaaaabaaaaaamgaabaaaabaaaaaadiaaaaaihcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiccaaaadaaaaaaanaaaaaadcaaaaakhcaabaaaaaaaaaaaegiccaaa
adaaaaaaamaaaaaaagbabaaaaaaaaaaaegacbaaaaaaaaaaadcaaaaakhcaabaaa
aaaaaaaaegiccaaaadaaaaaaaoaaaaaakgbkbaaaaaaaaaaaegacbaaaaaaaaaaa
dcaaaaakhccabaaaacaaaaaaegiccaaaadaaaaaaapaaaaaapgbpbaaaaaaaaaaa
egacbaaaaaaaaaaadiaaaaaihcaabaaaaaaaaaaaegbcbaaaacaaaaaapgipcaaa
adaaaaaabeaaaaaadiaaaaaihcaabaaaabaaaaaafgafbaaaaaaaaaaaegiccaaa
adaaaaaaanaaaaaadcaaaaaklcaabaaaaaaaaaaaegiicaaaadaaaaaaamaaaaaa
agaabaaaaaaaaaaaegaibaaaabaaaaaadcaaaaakhccabaaaadaaaaaaegiccaaa
adaaaaaaaoaaaaaakgakbaaaaaaaaaaaegadbaaaaaaaaaaadgaaaaaghccabaaa
aeaaaaaaegiccaaaacaaaaaaaaaaaaaadiaaaaaipcaabaaaaaaaaaaafgbfbaaa
aaaaaaaaegiocaaaadaaaaaaanaaaaaadcaaaaakpcaabaaaaaaaaaaaegiocaaa
adaaaaaaamaaaaaaagbabaaaaaaaaaaaegaobaaaaaaaaaaadcaaaaakpcaabaaa
aaaaaaaaegiocaaaadaaaaaaaoaaaaaakgbkbaaaaaaaaaaaegaobaaaaaaaaaaa
dcaaaaakpcaabaaaaaaaaaaaegiocaaaadaaaaaaapaaaaaapgbpbaaaaaaaaaaa
egaobaaaaaaaaaaadiaaaaaidcaabaaaabaaaaaafgafbaaaaaaaaaaaegiacaaa
aaaaaaaaaeaaaaaadcaaaaakdcaabaaaaaaaaaaaegiacaaaaaaaaaaaadaaaaaa
agaabaaaaaaaaaaaegaabaaaabaaaaaadcaaaaakdcaabaaaaaaaaaaaegiacaaa
aaaaaaaaafaaaaaakgakbaaaaaaaaaaaegaabaaaaaaaaaaadcaaaaakdccabaaa
afaaaaaaegiacaaaaaaaaaaaagaaaaaapgapbaaaaaaaaaaaegaabaaaaaaaaaaa
doaaaaab"
}
}
Program "fp" {
SubProgram "d3d11 " {
Keywords { "POINT" }
SetTexture 0 [_CameraDepthTexture] 2D 1
SetTexture 1 [_Background] 2D 2
SetTexture 2 [Volume] 3D 0
ConstBuffer "$Globals" 256
Vector 112 [screenCorner]
Vector 128 [cameraUp]
Vector 144 [cameraRight]
Vector 160 [cameraWorldSize]
Float 176 [StepSize]
Vector 192 [worldOrigin]
Float 208 [halfWorldSize]
Float 212 [transparency]
Vector 224 [bored]
Float 240 [minF]
Float 244 [maxF]
ConstBuffer "UnityPerCamera" 128
Vector 64 [_WorldSpaceCameraPos] 3
Vector 112 [_ZBufferParams]
BindCB  "$Globals" 0
BindCB  "UnityPerCamera" 1
"ps_5_0
eefiecedclaejlkoplllfcooahnhogjhmgfglmghabaaaaaagaalaaaaadaaaaaa
cmaaaaaaoeaaaaaabiabaaaaejfdeheolaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaakeaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapalaaaakeaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaakeaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaaahaaaaaakeaaaaaa
adaaaaaaaaaaaaaaadaaaaaaaeaaaaaaahaaaaaakeaaaaaaaeaaaaaaaaaaaaaa
adaaaaaaafaaaaaaahaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfcee
aaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgfheaaklklfdeieffieaakaaaa
faaaaaaajaacaaaagkaiaaabfjaaaaaeegiocaaaaaaaaaaabaaaaaaafjaaaaae
egiocaaaabaaaaaaaiaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaa
fibiaaaeaahabaaaabaaaaaaffffaaaaficiaaaeaahabaaaacaaaaaaffffaaaa
gcbaaaadlcbabaaaabaaaaaagcbaaaadhcbabaaaacaaaaaagfaaaaadpccabaaa
aaaaaaaagiaaaaacafaaaaaaaoaaaaahdcaabaaaaaaaaaaaegbabaaaabaaaaaa
pgbpbaaaabaaaaaadiaaaaajhcaabaaaabaaaaaaegiccaaaaaaaaaaaaiaaaaaa
fgifcaaaaaaaaaaaakaaaaaadcaaaaakhcaabaaaabaaaaaaegacbaaaabaaaaaa
fgafbaaaaaaaaaaaegiccaaaaaaaaaaaahaaaaaadiaaaaajhcaabaaaacaaaaaa
egiccaaaaaaaaaaaajaaaaaaagiacaaaaaaaaaaaakaaaaaadcaaaaajhcaabaaa
abaaaaaaegacbaaaacaaaaaaagaabaaaaaaaaaaaegacbaaaabaaaaaaaaaaaaai
hcaabaaaacaaaaaaegacbaiaebaaaaaaabaaaaaaegbcbaaaacaaaaaabaaaaaah
ecaabaaaaaaaaaaaegacbaaaacaaaaaaegacbaaaacaaaaaaeeaaaaafecaabaaa
aaaaaaaackaabaaaaaaaaaaadiaaaaahhcaabaaaacaaaaaakgakbaaaaaaaaaaa
egacbaaaacaaaaaaefaaaailmcaaaaiaedffbfaaecaabaaaaaaaaaaaegaabaaa
aaaaaaaajghmbaaaaaaaaaaaaagabaaaabaaaaaaefaaaailmcaaaaiaedffbfaa
lcaabaaaaaaaaaaaegaabaaaaaaaaaaaeghlbaaaabaaaaaaaagabaaaacaaaaaa
dcaaaaalecaabaaaaaaaaaaackiacaaaabaaaaaaahaaaaaackaabaaaaaaaaaaa
dkiacaaaabaaaaaaahaaaaaaaoaaaaakecaabaaaaaaaaaaaaceaaaaaaaaaiadp
aaaaiadpaaaaiadpaaaaiadpckaabaaaaaaaaaaaaaaaaaajicaabaaaabaaaaaa
akiacaaaaaaaaaaaanaaaaaaakiacaaaaaaaaaaaanaaaaaadgaaaaafhcaabaaa
adaaaaaaegacbaaaabaaaaaadgaaaaaficaabaaaacaaaaaaabeaaaaaaaaaaaaa
dgaaaaaficaabaaaadaaaaaaabeaaaaaaaaaaaaadaaaaaabcbaaaaahbcaabaaa
aeaaaaaadkaabaaaadaaaaaaabeaaaaaaaabaaaaadaaaeadakaabaaaaeaaaaaa
aaaaaaajhcaabaaaaeaaaaaaegacbaiaebaaaaaaadaaaaaaegiccaaaabaaaaaa
aeaaaaaabaaaaaahbcaabaaaaeaaaaaaegacbaaaaeaaaaaaegacbaaaaeaaaaaa
elaaaaafbcaabaaaaeaaaaaaakaabaaaaeaaaaaabnaaaaahbcaabaaaaeaaaaaa
akaabaaaaeaaaaaackaabaaaaaaaaaaabpaaaeadakaabaaaaeaaaaaaacaaaaab
bfaaaaabaaaaaaajhcaabaaaaeaaaaaaegacbaaaadaaaaaaegiccaiaebaaaaaa
aaaaaaaaamaaaaaaaaaaaaaihcaabaaaaeaaaaaaegacbaaaaeaaaaaaagiacaaa
aaaaaaaaanaaaaaaaoaaaaahhcaabaaaaeaaaaaaegacbaaaaeaaaaaapgapbaaa
abaaaaaaeiaaaainecabaaiaedffbfaabcaabaaaaeaaaaaaegacbaaaaeaaaaaa
eghobaaaacaaaaaaaagabaaaaaaaaaaaabeaaaaaaaaaaaaadjaaaaahccaabaaa
aeaaaaaaakaabaaaaeaaaaaaabeaaaaaaaaaaaaacpaaaaagbcaabaaaaeaaaaaa
akaabaiaibaaaaaaaeaaaaaadiaaaaahbcaabaaaaeaaaaaaakaabaaaaeaaaaaa
abeaaaaajlcajkdoaaaaaaaibcaabaaaaeaaaaaaakaabaiambaaaaaaaeaaaaaa
abeaaaaaaaaaiadpabaaaaahbcaabaaaaeaaaaaaakaabaaaaeaaaaaabkaabaaa
aeaaaaaadiaaaaaibcaabaaaaeaaaaaaakaabaaaaeaaaaaabkiacaaaaaaaaaaa
anaaaaaaaaaaaaaiccaabaaaaeaaaaaadkaabaiaebaaaaaaacaaaaaaabeaaaaa
aaaaiadpdcaaaaajicaabaaaacaaaaaabkaabaaaaeaaaaaaakaabaaaaeaaaaaa
dkaabaaaacaaaaaadcaaaaakhcaabaaaadaaaaaaegacbaaaacaaaaaaagiacaaa
aaaaaaaaalaaaaaaegacbaaaadaaaaaaboaaaaahicaabaaaadaaaaaadkaabaaa
adaaaaaaabeaaaaaabaaaaaabgaaaaabaaaaaaaiecaabaaaaaaaaaaadkaabaia
ebaaaaaaacaaaaaaabeaaaaaaaaaiadpdiaaaaaihcaabaaaabaaaaaakgakbaaa
aaaaaaaaegiccaaaaaaaaaaaaoaaaaaadeaaaaahecaabaaaaaaaaaaadkaabaaa
aaaaaaaabkaabaaaaaaaaaaadeaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaa
akaabaaaaaaaaaaaddaaaaahicaabaaaabaaaaaadkaabaaaaaaaaaaabkaabaaa
aaaaaaaaddaaaaahicaabaaaabaaaaaaakaabaaaaaaaaaaadkaabaaaabaaaaaa
aaaaaaaiicaabaaaabaaaaaackaabaaaaaaaaaaadkaabaiaebaaaaaaabaaaaaa
djaaaaahbcaabaaaacaaaaaadkaabaaaabaaaaaaabeaaaaaaaaaaaaaaaaaaaai
ocaabaaaacaaaaaaaganbaiaebaaaaaaaaaaaaaakgakbaaaaaaaaaaaaoaaaaah
ocaabaaaacaaaaaafgaobaaaacaaaaaapgapbaaaabaaaaaaaaaaaaaiocaabaaa
acaaaaaapgajbaiaebaaaaaaacaaaaaafgaobaaaacaaaaaaaaaaaaakgcaabaaa
acaaaaaafgagbaaaacaaaaaaaceaaaaaaaaaaaaaaaaaaaeaaaaaiaeaaaaaaaaa
bnaaaaahdcaabaaaaaaaaaaaegaabaaaaaaaaaaakgakbaaaaaaaaaaadhaaaaaj
ccaabaaaaaaaaaaabkaabaaaaaaaaaaabkaabaaaacaaaaaackaabaaaacaaaaaa
dhaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaadkaabaaaacaaaaaabkaabaaa
aaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaklkkckdo
bkaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabaaaaahbcaabaaaaaaaaaaa
akaabaaaaaaaaaaaakaabaaaacaaaaaadeaaaaahccaabaaaaaaaaaaackaabaaa
abaaaaaabkaabaaaabaaaaaadeaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaa
akaabaaaabaaaaaaddaaaaahecaabaaaaaaaaaaackaabaaaabaaaaaabkaabaaa
abaaaaaaddaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaaakaabaaaabaaaaaa
aaaaaaaiecaabaaaaaaaaaaackaabaiaebaaaaaaaaaaaaaabkaabaaaaaaaaaaa
djaaaaahicaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaaaaaaoaaaaah
ecaabaaaaaaaaaaackaabaaaaaaaaaaabkaabaaaaaaaaaaaabaaaaahecaabaaa
aaaaaaaackaabaaaaaaaaaaadkaabaaaaaaaaaaadcaaaaaphcaabaaaacaaaaaa
agaabaaaaaaaaaaaaceaaaaaaaaamaeaaaaamaeaaaaamaeaaaaaaaaaaceaaaaa
aaaaeamaaaaaaamaaaaaiamaaaaaaaaadccaaabahcaabaaaacaaaaaaegacbaia
ibaaaaaaacaaaaaaaceaaaaaaaaaiadpaaaaialpaaaaialpaaaaaaaaaceaaaaa
aaaaialpaaaaaaeaaaaaaaeaaaaaaaaaaaaaaaakhcaabaaaacaaaaaaegacbaaa
acaaaaaaaceaaaaaaaaaialpaaaaialpaaaaialpaaaaaaaadcaaaaamncaabaaa
aaaaaaaaagajbaaaacaaaaaakgakbaaaaaaaaaaaaceaaaaaaaaaiadpaaaaaaaa
aaaaiadpaaaaiadpdiaaaaahncaabaaaaaaaaaaafgafbaaaaaaaaaaaagaobaaa
aaaaaaaaaaaaaaajccaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaiaebaaaaaa
aaaaaaaaapaaaaaadeaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaa
aaaaaaaaaaaaaaakicaabaaaabaaaaaaakiacaiaebaaaaaaaaaaaaaaapaaaaaa
bkiacaaaaaaaaaaaapaaaaaaaoaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaa
dkaabaaaabaaaaaaaaaaaaaiicaabaaaabaaaaaabkaabaiaebaaaaaaaaaaaaaa
abeaaaaaaaaaiadpdiaaaaahhcaabaaaaaaaaaaaigadbaaaaaaaaaaafgafbaaa
aaaaaaaadcaaaaajhccabaaaaaaaaaaapgapbaaaabaaaaaaegacbaaaabaaaaaa
egacbaaaaaaaaaaadgaaaaaficcabaaaaaaaaaaaabeaaaaaaaaaiadpdoaaaaab
"
}
SubProgram "d3d11 " {
Keywords { "DIRECTIONAL" }
SetTexture 0 [_CameraDepthTexture] 2D 1
SetTexture 1 [_Background] 2D 2
SetTexture 2 [Volume] 3D 0
ConstBuffer "$Globals" 192
Vector 48 [screenCorner]
Vector 64 [cameraUp]
Vector 80 [cameraRight]
Vector 96 [cameraWorldSize]
Float 112 [StepSize]
Vector 128 [worldOrigin]
Float 144 [halfWorldSize]
Float 148 [transparency]
Vector 160 [bored]
Float 176 [minF]
Float 180 [maxF]
ConstBuffer "UnityPerCamera" 128
Vector 64 [_WorldSpaceCameraPos] 3
Vector 112 [_ZBufferParams]
BindCB  "$Globals" 0
BindCB  "UnityPerCamera" 1
"ps_5_0
eefiecedjindbgeemlbhhdfpifiejgehlegpmeccabaaaaaaeialaaaaadaaaaaa
cmaaaaaammaaaaaaaaabaaaaejfdeheojiaaaaaaafaaaaaaaiaaaaaaiaaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaaimaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapalaaaaimaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaaimaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaaahaaaaaaimaaaaaa
adaaaaaaaaaaaaaaadaaaaaaaeaaaaaaahaaaaaafdfgfpfaepfdejfeejepeoaa
feeffiedepepfceeaaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaacaaaaaaa
aaaaaaaaaaaaaaaaadaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgfheaaklkl
fdeieffieaakaaaafaaaaaaajaacaaaagkaiaaabfjaaaaaeegiocaaaaaaaaaaa
amaaaaaafjaaaaaeegiocaaaabaaaaaaaiaaaaaafkaaaaadaagabaaaaaaaaaaa
fkaaaaadaagabaaaabaaaaaafkaaaaadaagabaaaacaaaaaafibiaaaeaahabaaa
aaaaaaaaffffaaaafibiaaaeaahabaaaabaaaaaaffffaaaaficiaaaeaahabaaa
acaaaaaaffffaaaagcbaaaadlcbabaaaabaaaaaagcbaaaadhcbabaaaacaaaaaa
gfaaaaadpccabaaaaaaaaaaagiaaaaacafaaaaaaaoaaaaahdcaabaaaaaaaaaaa
egbabaaaabaaaaaapgbpbaaaabaaaaaadiaaaaajhcaabaaaabaaaaaaegiccaaa
aaaaaaaaaeaaaaaafgifcaaaaaaaaaaaagaaaaaadcaaaaakhcaabaaaabaaaaaa
egacbaaaabaaaaaafgafbaaaaaaaaaaaegiccaaaaaaaaaaaadaaaaaadiaaaaaj
hcaabaaaacaaaaaaegiccaaaaaaaaaaaafaaaaaaagiacaaaaaaaaaaaagaaaaaa
dcaaaaajhcaabaaaabaaaaaaegacbaaaacaaaaaaagaabaaaaaaaaaaaegacbaaa
abaaaaaaaaaaaaaihcaabaaaacaaaaaaegacbaiaebaaaaaaabaaaaaaegbcbaaa
acaaaaaabaaaaaahecaabaaaaaaaaaaaegacbaaaacaaaaaaegacbaaaacaaaaaa
eeaaaaafecaabaaaaaaaaaaackaabaaaaaaaaaaadiaaaaahhcaabaaaacaaaaaa
kgakbaaaaaaaaaaaegacbaaaacaaaaaaefaaaailmcaaaaiaedffbfaaecaabaaa
aaaaaaaaegaabaaaaaaaaaaajghmbaaaaaaaaaaaaagabaaaabaaaaaaefaaaail
mcaaaaiaedffbfaalcaabaaaaaaaaaaaegaabaaaaaaaaaaaeghlbaaaabaaaaaa
aagabaaaacaaaaaadcaaaaalecaabaaaaaaaaaaackiacaaaabaaaaaaahaaaaaa
ckaabaaaaaaaaaaadkiacaaaabaaaaaaahaaaaaaaoaaaaakecaabaaaaaaaaaaa
aceaaaaaaaaaiadpaaaaiadpaaaaiadpaaaaiadpckaabaaaaaaaaaaaaaaaaaaj
icaabaaaabaaaaaaakiacaaaaaaaaaaaajaaaaaaakiacaaaaaaaaaaaajaaaaaa
dgaaaaafhcaabaaaadaaaaaaegacbaaaabaaaaaadgaaaaaficaabaaaacaaaaaa
abeaaaaaaaaaaaaadgaaaaaficaabaaaadaaaaaaabeaaaaaaaaaaaaadaaaaaab
cbaaaaahbcaabaaaaeaaaaaadkaabaaaadaaaaaaabeaaaaaaaabaaaaadaaaead
akaabaaaaeaaaaaaaaaaaaajhcaabaaaaeaaaaaaegacbaiaebaaaaaaadaaaaaa
egiccaaaabaaaaaaaeaaaaaabaaaaaahbcaabaaaaeaaaaaaegacbaaaaeaaaaaa
egacbaaaaeaaaaaaelaaaaafbcaabaaaaeaaaaaaakaabaaaaeaaaaaabnaaaaah
bcaabaaaaeaaaaaaakaabaaaaeaaaaaackaabaaaaaaaaaaabpaaaeadakaabaaa
aeaaaaaaacaaaaabbfaaaaabaaaaaaajhcaabaaaaeaaaaaaegacbaaaadaaaaaa
egiccaiaebaaaaaaaaaaaaaaaiaaaaaaaaaaaaaihcaabaaaaeaaaaaaegacbaaa
aeaaaaaaagiacaaaaaaaaaaaajaaaaaaaoaaaaahhcaabaaaaeaaaaaaegacbaaa
aeaaaaaapgapbaaaabaaaaaaeiaaaainecabaaiaedffbfaabcaabaaaaeaaaaaa
egacbaaaaeaaaaaaeghobaaaacaaaaaaaagabaaaaaaaaaaaabeaaaaaaaaaaaaa
djaaaaahccaabaaaaeaaaaaaakaabaaaaeaaaaaaabeaaaaaaaaaaaaacpaaaaag
bcaabaaaaeaaaaaaakaabaiaibaaaaaaaeaaaaaadiaaaaahbcaabaaaaeaaaaaa
akaabaaaaeaaaaaaabeaaaaajlcajkdoaaaaaaaibcaabaaaaeaaaaaaakaabaia
mbaaaaaaaeaaaaaaabeaaaaaaaaaiadpabaaaaahbcaabaaaaeaaaaaaakaabaaa
aeaaaaaabkaabaaaaeaaaaaadiaaaaaibcaabaaaaeaaaaaaakaabaaaaeaaaaaa
bkiacaaaaaaaaaaaajaaaaaaaaaaaaaiccaabaaaaeaaaaaadkaabaiaebaaaaaa
acaaaaaaabeaaaaaaaaaiadpdcaaaaajicaabaaaacaaaaaabkaabaaaaeaaaaaa
akaabaaaaeaaaaaadkaabaaaacaaaaaadcaaaaakhcaabaaaadaaaaaaegacbaaa
acaaaaaaagiacaaaaaaaaaaaahaaaaaaegacbaaaadaaaaaaboaaaaahicaabaaa
adaaaaaadkaabaaaadaaaaaaabeaaaaaabaaaaaabgaaaaabaaaaaaaiecaabaaa
aaaaaaaadkaabaiaebaaaaaaacaaaaaaabeaaaaaaaaaiadpdiaaaaaihcaabaaa
abaaaaaakgakbaaaaaaaaaaaegiccaaaaaaaaaaaakaaaaaadeaaaaahecaabaaa
aaaaaaaadkaabaaaaaaaaaaabkaabaaaaaaaaaaadeaaaaahecaabaaaaaaaaaaa
ckaabaaaaaaaaaaaakaabaaaaaaaaaaaddaaaaahicaabaaaabaaaaaadkaabaaa
aaaaaaaabkaabaaaaaaaaaaaddaaaaahicaabaaaabaaaaaaakaabaaaaaaaaaaa
dkaabaaaabaaaaaaaaaaaaaiicaabaaaabaaaaaackaabaaaaaaaaaaadkaabaia
ebaaaaaaabaaaaaadjaaaaahbcaabaaaacaaaaaadkaabaaaabaaaaaaabeaaaaa
aaaaaaaaaaaaaaaiocaabaaaacaaaaaaaganbaiaebaaaaaaaaaaaaaakgakbaaa
aaaaaaaaaoaaaaahocaabaaaacaaaaaafgaobaaaacaaaaaapgapbaaaabaaaaaa
aaaaaaaiocaabaaaacaaaaaapgajbaiaebaaaaaaacaaaaaafgaobaaaacaaaaaa
aaaaaaakgcaabaaaacaaaaaafgagbaaaacaaaaaaaceaaaaaaaaaaaaaaaaaaaea
aaaaiaeaaaaaaaaabnaaaaahdcaabaaaaaaaaaaaegaabaaaaaaaaaaakgakbaaa
aaaaaaaadhaaaaajccaabaaaaaaaaaaabkaabaaaaaaaaaaabkaabaaaacaaaaaa
ckaabaaaacaaaaaadhaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaadkaabaaa
acaaaaaabkaabaaaaaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaa
abeaaaaaklkkckdobkaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabaaaaah
bcaabaaaaaaaaaaaakaabaaaaaaaaaaaakaabaaaacaaaaaadeaaaaahccaabaaa
aaaaaaaackaabaaaabaaaaaabkaabaaaabaaaaaadeaaaaahccaabaaaaaaaaaaa
bkaabaaaaaaaaaaaakaabaaaabaaaaaaddaaaaahecaabaaaaaaaaaaackaabaaa
abaaaaaabkaabaaaabaaaaaaddaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaa
akaabaaaabaaaaaaaaaaaaaiecaabaaaaaaaaaaackaabaiaebaaaaaaaaaaaaaa
bkaabaaaaaaaaaaadjaaaaahicaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaa
aaaaaaaaaoaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaabkaabaaaaaaaaaaa
abaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaadkaabaaaaaaaaaaadcaaaaap
hcaabaaaacaaaaaaagaabaaaaaaaaaaaaceaaaaaaaaamaeaaaaamaeaaaaamaea
aaaaaaaaaceaaaaaaaaaeamaaaaaaamaaaaaiamaaaaaaaaadccaaabahcaabaaa
acaaaaaaegacbaiaibaaaaaaacaaaaaaaceaaaaaaaaaiadpaaaaialpaaaaialp
aaaaaaaaaceaaaaaaaaaialpaaaaaaeaaaaaaaeaaaaaaaaaaaaaaaakhcaabaaa
acaaaaaaegacbaaaacaaaaaaaceaaaaaaaaaialpaaaaialpaaaaialpaaaaaaaa
dcaaaaamncaabaaaaaaaaaaaagajbaaaacaaaaaakgakbaaaaaaaaaaaaceaaaaa
aaaaiadpaaaaaaaaaaaaiadpaaaaiadpdiaaaaahncaabaaaaaaaaaaafgafbaaa
aaaaaaaaagaobaaaaaaaaaaaaaaaaaajccaabaaaaaaaaaaabkaabaaaaaaaaaaa
akiacaiaebaaaaaaaaaaaaaaalaaaaaadeaaaaahccaabaaaaaaaaaaabkaabaaa
aaaaaaaaabeaaaaaaaaaaaaaaaaaaaakicaabaaaabaaaaaaakiacaiaebaaaaaa
aaaaaaaaalaaaaaabkiacaaaaaaaaaaaalaaaaaaaoaaaaahccaabaaaaaaaaaaa
bkaabaaaaaaaaaaadkaabaaaabaaaaaaaaaaaaaiicaabaaaabaaaaaabkaabaia
ebaaaaaaaaaaaaaaabeaaaaaaaaaiadpdiaaaaahhcaabaaaaaaaaaaaigadbaaa
aaaaaaaafgafbaaaaaaaaaaadcaaaaajhccabaaaaaaaaaaapgapbaaaabaaaaaa
egacbaaaabaaaaaaegacbaaaaaaaaaaadgaaaaaficcabaaaaaaaaaaaabeaaaaa
aaaaiadpdoaaaaab"
}
SubProgram "d3d11 " {
Keywords { "SPOT" }
SetTexture 0 [_CameraDepthTexture] 2D 1
SetTexture 1 [_Background] 2D 2
SetTexture 2 [Volume] 3D 0
ConstBuffer "$Globals" 256
Vector 112 [screenCorner]
Vector 128 [cameraUp]
Vector 144 [cameraRight]
Vector 160 [cameraWorldSize]
Float 176 [StepSize]
Vector 192 [worldOrigin]
Float 208 [halfWorldSize]
Float 212 [transparency]
Vector 224 [bored]
Float 240 [minF]
Float 244 [maxF]
ConstBuffer "UnityPerCamera" 128
Vector 64 [_WorldSpaceCameraPos] 3
Vector 112 [_ZBufferParams]
BindCB  "$Globals" 0
BindCB  "UnityPerCamera" 1
"ps_5_0
eefieceddidhbijcalagiidbldeogkifnpjmodfiabaaaaaagaalaaaaadaaaaaa
cmaaaaaaoeaaaaaabiabaaaaejfdeheolaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaakeaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapalaaaakeaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaakeaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaaahaaaaaakeaaaaaa
adaaaaaaaaaaaaaaadaaaaaaaeaaaaaaahaaaaaakeaaaaaaaeaaaaaaaaaaaaaa
adaaaaaaafaaaaaaapaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfcee
aaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgfheaaklklfdeieffieaakaaaa
faaaaaaajaacaaaagkaiaaabfjaaaaaeegiocaaaaaaaaaaabaaaaaaafjaaaaae
egiocaaaabaaaaaaaiaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaa
fibiaaaeaahabaaaabaaaaaaffffaaaaficiaaaeaahabaaaacaaaaaaffffaaaa
gcbaaaadlcbabaaaabaaaaaagcbaaaadhcbabaaaacaaaaaagfaaaaadpccabaaa
aaaaaaaagiaaaaacafaaaaaaaoaaaaahdcaabaaaaaaaaaaaegbabaaaabaaaaaa
pgbpbaaaabaaaaaadiaaaaajhcaabaaaabaaaaaaegiccaaaaaaaaaaaaiaaaaaa
fgifcaaaaaaaaaaaakaaaaaadcaaaaakhcaabaaaabaaaaaaegacbaaaabaaaaaa
fgafbaaaaaaaaaaaegiccaaaaaaaaaaaahaaaaaadiaaaaajhcaabaaaacaaaaaa
egiccaaaaaaaaaaaajaaaaaaagiacaaaaaaaaaaaakaaaaaadcaaaaajhcaabaaa
abaaaaaaegacbaaaacaaaaaaagaabaaaaaaaaaaaegacbaaaabaaaaaaaaaaaaai
hcaabaaaacaaaaaaegacbaiaebaaaaaaabaaaaaaegbcbaaaacaaaaaabaaaaaah
ecaabaaaaaaaaaaaegacbaaaacaaaaaaegacbaaaacaaaaaaeeaaaaafecaabaaa
aaaaaaaackaabaaaaaaaaaaadiaaaaahhcaabaaaacaaaaaakgakbaaaaaaaaaaa
egacbaaaacaaaaaaefaaaailmcaaaaiaedffbfaaecaabaaaaaaaaaaaegaabaaa
aaaaaaaajghmbaaaaaaaaaaaaagabaaaabaaaaaaefaaaailmcaaaaiaedffbfaa
lcaabaaaaaaaaaaaegaabaaaaaaaaaaaeghlbaaaabaaaaaaaagabaaaacaaaaaa
dcaaaaalecaabaaaaaaaaaaackiacaaaabaaaaaaahaaaaaackaabaaaaaaaaaaa
dkiacaaaabaaaaaaahaaaaaaaoaaaaakecaabaaaaaaaaaaaaceaaaaaaaaaiadp
aaaaiadpaaaaiadpaaaaiadpckaabaaaaaaaaaaaaaaaaaajicaabaaaabaaaaaa
akiacaaaaaaaaaaaanaaaaaaakiacaaaaaaaaaaaanaaaaaadgaaaaafhcaabaaa
adaaaaaaegacbaaaabaaaaaadgaaaaaficaabaaaacaaaaaaabeaaaaaaaaaaaaa
dgaaaaaficaabaaaadaaaaaaabeaaaaaaaaaaaaadaaaaaabcbaaaaahbcaabaaa
aeaaaaaadkaabaaaadaaaaaaabeaaaaaaaabaaaaadaaaeadakaabaaaaeaaaaaa
aaaaaaajhcaabaaaaeaaaaaaegacbaiaebaaaaaaadaaaaaaegiccaaaabaaaaaa
aeaaaaaabaaaaaahbcaabaaaaeaaaaaaegacbaaaaeaaaaaaegacbaaaaeaaaaaa
elaaaaafbcaabaaaaeaaaaaaakaabaaaaeaaaaaabnaaaaahbcaabaaaaeaaaaaa
akaabaaaaeaaaaaackaabaaaaaaaaaaabpaaaeadakaabaaaaeaaaaaaacaaaaab
bfaaaaabaaaaaaajhcaabaaaaeaaaaaaegacbaaaadaaaaaaegiccaiaebaaaaaa
aaaaaaaaamaaaaaaaaaaaaaihcaabaaaaeaaaaaaegacbaaaaeaaaaaaagiacaaa
aaaaaaaaanaaaaaaaoaaaaahhcaabaaaaeaaaaaaegacbaaaaeaaaaaapgapbaaa
abaaaaaaeiaaaainecabaaiaedffbfaabcaabaaaaeaaaaaaegacbaaaaeaaaaaa
eghobaaaacaaaaaaaagabaaaaaaaaaaaabeaaaaaaaaaaaaadjaaaaahccaabaaa
aeaaaaaaakaabaaaaeaaaaaaabeaaaaaaaaaaaaacpaaaaagbcaabaaaaeaaaaaa
akaabaiaibaaaaaaaeaaaaaadiaaaaahbcaabaaaaeaaaaaaakaabaaaaeaaaaaa
abeaaaaajlcajkdoaaaaaaaibcaabaaaaeaaaaaaakaabaiambaaaaaaaeaaaaaa
abeaaaaaaaaaiadpabaaaaahbcaabaaaaeaaaaaaakaabaaaaeaaaaaabkaabaaa
aeaaaaaadiaaaaaibcaabaaaaeaaaaaaakaabaaaaeaaaaaabkiacaaaaaaaaaaa
anaaaaaaaaaaaaaiccaabaaaaeaaaaaadkaabaiaebaaaaaaacaaaaaaabeaaaaa
aaaaiadpdcaaaaajicaabaaaacaaaaaabkaabaaaaeaaaaaaakaabaaaaeaaaaaa
dkaabaaaacaaaaaadcaaaaakhcaabaaaadaaaaaaegacbaaaacaaaaaaagiacaaa
aaaaaaaaalaaaaaaegacbaaaadaaaaaaboaaaaahicaabaaaadaaaaaadkaabaaa
adaaaaaaabeaaaaaabaaaaaabgaaaaabaaaaaaaiecaabaaaaaaaaaaadkaabaia
ebaaaaaaacaaaaaaabeaaaaaaaaaiadpdiaaaaaihcaabaaaabaaaaaakgakbaaa
aaaaaaaaegiccaaaaaaaaaaaaoaaaaaadeaaaaahecaabaaaaaaaaaaadkaabaaa
aaaaaaaabkaabaaaaaaaaaaadeaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaa
akaabaaaaaaaaaaaddaaaaahicaabaaaabaaaaaadkaabaaaaaaaaaaabkaabaaa
aaaaaaaaddaaaaahicaabaaaabaaaaaaakaabaaaaaaaaaaadkaabaaaabaaaaaa
aaaaaaaiicaabaaaabaaaaaackaabaaaaaaaaaaadkaabaiaebaaaaaaabaaaaaa
djaaaaahbcaabaaaacaaaaaadkaabaaaabaaaaaaabeaaaaaaaaaaaaaaaaaaaai
ocaabaaaacaaaaaaaganbaiaebaaaaaaaaaaaaaakgakbaaaaaaaaaaaaoaaaaah
ocaabaaaacaaaaaafgaobaaaacaaaaaapgapbaaaabaaaaaaaaaaaaaiocaabaaa
acaaaaaapgajbaiaebaaaaaaacaaaaaafgaobaaaacaaaaaaaaaaaaakgcaabaaa
acaaaaaafgagbaaaacaaaaaaaceaaaaaaaaaaaaaaaaaaaeaaaaaiaeaaaaaaaaa
bnaaaaahdcaabaaaaaaaaaaaegaabaaaaaaaaaaakgakbaaaaaaaaaaadhaaaaaj
ccaabaaaaaaaaaaabkaabaaaaaaaaaaabkaabaaaacaaaaaackaabaaaacaaaaaa
dhaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaadkaabaaaacaaaaaabkaabaaa
aaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaklkkckdo
bkaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabaaaaahbcaabaaaaaaaaaaa
akaabaaaaaaaaaaaakaabaaaacaaaaaadeaaaaahccaabaaaaaaaaaaackaabaaa
abaaaaaabkaabaaaabaaaaaadeaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaa
akaabaaaabaaaaaaddaaaaahecaabaaaaaaaaaaackaabaaaabaaaaaabkaabaaa
abaaaaaaddaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaaakaabaaaabaaaaaa
aaaaaaaiecaabaaaaaaaaaaackaabaiaebaaaaaaaaaaaaaabkaabaaaaaaaaaaa
djaaaaahicaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaaaaaaoaaaaah
ecaabaaaaaaaaaaackaabaaaaaaaaaaabkaabaaaaaaaaaaaabaaaaahecaabaaa
aaaaaaaackaabaaaaaaaaaaadkaabaaaaaaaaaaadcaaaaaphcaabaaaacaaaaaa
agaabaaaaaaaaaaaaceaaaaaaaaamaeaaaaamaeaaaaamaeaaaaaaaaaaceaaaaa
aaaaeamaaaaaaamaaaaaiamaaaaaaaaadccaaabahcaabaaaacaaaaaaegacbaia
ibaaaaaaacaaaaaaaceaaaaaaaaaiadpaaaaialpaaaaialpaaaaaaaaaceaaaaa
aaaaialpaaaaaaeaaaaaaaeaaaaaaaaaaaaaaaakhcaabaaaacaaaaaaegacbaaa
acaaaaaaaceaaaaaaaaaialpaaaaialpaaaaialpaaaaaaaadcaaaaamncaabaaa
aaaaaaaaagajbaaaacaaaaaakgakbaaaaaaaaaaaaceaaaaaaaaaiadpaaaaaaaa
aaaaiadpaaaaiadpdiaaaaahncaabaaaaaaaaaaafgafbaaaaaaaaaaaagaobaaa
aaaaaaaaaaaaaaajccaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaiaebaaaaaa
aaaaaaaaapaaaaaadeaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaa
aaaaaaaaaaaaaaakicaabaaaabaaaaaaakiacaiaebaaaaaaaaaaaaaaapaaaaaa
bkiacaaaaaaaaaaaapaaaaaaaoaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaa
dkaabaaaabaaaaaaaaaaaaaiicaabaaaabaaaaaabkaabaiaebaaaaaaaaaaaaaa
abeaaaaaaaaaiadpdiaaaaahhcaabaaaaaaaaaaaigadbaaaaaaaaaaafgafbaaa
aaaaaaaadcaaaaajhccabaaaaaaaaaaapgapbaaaabaaaaaaegacbaaaabaaaaaa
egacbaaaaaaaaaaadgaaaaaficcabaaaaaaaaaaaabeaaaaaaaaaiadpdoaaaaab
"
}
SubProgram "d3d11 " {
Keywords { "POINT_COOKIE" }
SetTexture 0 [_CameraDepthTexture] 2D 1
SetTexture 1 [_Background] 2D 2
SetTexture 2 [Volume] 3D 0
ConstBuffer "$Globals" 256
Vector 112 [screenCorner]
Vector 128 [cameraUp]
Vector 144 [cameraRight]
Vector 160 [cameraWorldSize]
Float 176 [StepSize]
Vector 192 [worldOrigin]
Float 208 [halfWorldSize]
Float 212 [transparency]
Vector 224 [bored]
Float 240 [minF]
Float 244 [maxF]
ConstBuffer "UnityPerCamera" 128
Vector 64 [_WorldSpaceCameraPos] 3
Vector 112 [_ZBufferParams]
BindCB  "$Globals" 0
BindCB  "UnityPerCamera" 1
"ps_5_0
eefiecedclaejlkoplllfcooahnhogjhmgfglmghabaaaaaagaalaaaaadaaaaaa
cmaaaaaaoeaaaaaabiabaaaaejfdeheolaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaakeaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapalaaaakeaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaakeaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaaahaaaaaakeaaaaaa
adaaaaaaaaaaaaaaadaaaaaaaeaaaaaaahaaaaaakeaaaaaaaeaaaaaaaaaaaaaa
adaaaaaaafaaaaaaahaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfcee
aaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgfheaaklklfdeieffieaakaaaa
faaaaaaajaacaaaagkaiaaabfjaaaaaeegiocaaaaaaaaaaabaaaaaaafjaaaaae
egiocaaaabaaaaaaaiaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaa
fibiaaaeaahabaaaabaaaaaaffffaaaaficiaaaeaahabaaaacaaaaaaffffaaaa
gcbaaaadlcbabaaaabaaaaaagcbaaaadhcbabaaaacaaaaaagfaaaaadpccabaaa
aaaaaaaagiaaaaacafaaaaaaaoaaaaahdcaabaaaaaaaaaaaegbabaaaabaaaaaa
pgbpbaaaabaaaaaadiaaaaajhcaabaaaabaaaaaaegiccaaaaaaaaaaaaiaaaaaa
fgifcaaaaaaaaaaaakaaaaaadcaaaaakhcaabaaaabaaaaaaegacbaaaabaaaaaa
fgafbaaaaaaaaaaaegiccaaaaaaaaaaaahaaaaaadiaaaaajhcaabaaaacaaaaaa
egiccaaaaaaaaaaaajaaaaaaagiacaaaaaaaaaaaakaaaaaadcaaaaajhcaabaaa
abaaaaaaegacbaaaacaaaaaaagaabaaaaaaaaaaaegacbaaaabaaaaaaaaaaaaai
hcaabaaaacaaaaaaegacbaiaebaaaaaaabaaaaaaegbcbaaaacaaaaaabaaaaaah
ecaabaaaaaaaaaaaegacbaaaacaaaaaaegacbaaaacaaaaaaeeaaaaafecaabaaa
aaaaaaaackaabaaaaaaaaaaadiaaaaahhcaabaaaacaaaaaakgakbaaaaaaaaaaa
egacbaaaacaaaaaaefaaaailmcaaaaiaedffbfaaecaabaaaaaaaaaaaegaabaaa
aaaaaaaajghmbaaaaaaaaaaaaagabaaaabaaaaaaefaaaailmcaaaaiaedffbfaa
lcaabaaaaaaaaaaaegaabaaaaaaaaaaaeghlbaaaabaaaaaaaagabaaaacaaaaaa
dcaaaaalecaabaaaaaaaaaaackiacaaaabaaaaaaahaaaaaackaabaaaaaaaaaaa
dkiacaaaabaaaaaaahaaaaaaaoaaaaakecaabaaaaaaaaaaaaceaaaaaaaaaiadp
aaaaiadpaaaaiadpaaaaiadpckaabaaaaaaaaaaaaaaaaaajicaabaaaabaaaaaa
akiacaaaaaaaaaaaanaaaaaaakiacaaaaaaaaaaaanaaaaaadgaaaaafhcaabaaa
adaaaaaaegacbaaaabaaaaaadgaaaaaficaabaaaacaaaaaaabeaaaaaaaaaaaaa
dgaaaaaficaabaaaadaaaaaaabeaaaaaaaaaaaaadaaaaaabcbaaaaahbcaabaaa
aeaaaaaadkaabaaaadaaaaaaabeaaaaaaaabaaaaadaaaeadakaabaaaaeaaaaaa
aaaaaaajhcaabaaaaeaaaaaaegacbaiaebaaaaaaadaaaaaaegiccaaaabaaaaaa
aeaaaaaabaaaaaahbcaabaaaaeaaaaaaegacbaaaaeaaaaaaegacbaaaaeaaaaaa
elaaaaafbcaabaaaaeaaaaaaakaabaaaaeaaaaaabnaaaaahbcaabaaaaeaaaaaa
akaabaaaaeaaaaaackaabaaaaaaaaaaabpaaaeadakaabaaaaeaaaaaaacaaaaab
bfaaaaabaaaaaaajhcaabaaaaeaaaaaaegacbaaaadaaaaaaegiccaiaebaaaaaa
aaaaaaaaamaaaaaaaaaaaaaihcaabaaaaeaaaaaaegacbaaaaeaaaaaaagiacaaa
aaaaaaaaanaaaaaaaoaaaaahhcaabaaaaeaaaaaaegacbaaaaeaaaaaapgapbaaa
abaaaaaaeiaaaainecabaaiaedffbfaabcaabaaaaeaaaaaaegacbaaaaeaaaaaa
eghobaaaacaaaaaaaagabaaaaaaaaaaaabeaaaaaaaaaaaaadjaaaaahccaabaaa
aeaaaaaaakaabaaaaeaaaaaaabeaaaaaaaaaaaaacpaaaaagbcaabaaaaeaaaaaa
akaabaiaibaaaaaaaeaaaaaadiaaaaahbcaabaaaaeaaaaaaakaabaaaaeaaaaaa
abeaaaaajlcajkdoaaaaaaaibcaabaaaaeaaaaaaakaabaiambaaaaaaaeaaaaaa
abeaaaaaaaaaiadpabaaaaahbcaabaaaaeaaaaaaakaabaaaaeaaaaaabkaabaaa
aeaaaaaadiaaaaaibcaabaaaaeaaaaaaakaabaaaaeaaaaaabkiacaaaaaaaaaaa
anaaaaaaaaaaaaaiccaabaaaaeaaaaaadkaabaiaebaaaaaaacaaaaaaabeaaaaa
aaaaiadpdcaaaaajicaabaaaacaaaaaabkaabaaaaeaaaaaaakaabaaaaeaaaaaa
dkaabaaaacaaaaaadcaaaaakhcaabaaaadaaaaaaegacbaaaacaaaaaaagiacaaa
aaaaaaaaalaaaaaaegacbaaaadaaaaaaboaaaaahicaabaaaadaaaaaadkaabaaa
adaaaaaaabeaaaaaabaaaaaabgaaaaabaaaaaaaiecaabaaaaaaaaaaadkaabaia
ebaaaaaaacaaaaaaabeaaaaaaaaaiadpdiaaaaaihcaabaaaabaaaaaakgakbaaa
aaaaaaaaegiccaaaaaaaaaaaaoaaaaaadeaaaaahecaabaaaaaaaaaaadkaabaaa
aaaaaaaabkaabaaaaaaaaaaadeaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaa
akaabaaaaaaaaaaaddaaaaahicaabaaaabaaaaaadkaabaaaaaaaaaaabkaabaaa
aaaaaaaaddaaaaahicaabaaaabaaaaaaakaabaaaaaaaaaaadkaabaaaabaaaaaa
aaaaaaaiicaabaaaabaaaaaackaabaaaaaaaaaaadkaabaiaebaaaaaaabaaaaaa
djaaaaahbcaabaaaacaaaaaadkaabaaaabaaaaaaabeaaaaaaaaaaaaaaaaaaaai
ocaabaaaacaaaaaaaganbaiaebaaaaaaaaaaaaaakgakbaaaaaaaaaaaaoaaaaah
ocaabaaaacaaaaaafgaobaaaacaaaaaapgapbaaaabaaaaaaaaaaaaaiocaabaaa
acaaaaaapgajbaiaebaaaaaaacaaaaaafgaobaaaacaaaaaaaaaaaaakgcaabaaa
acaaaaaafgagbaaaacaaaaaaaceaaaaaaaaaaaaaaaaaaaeaaaaaiaeaaaaaaaaa
bnaaaaahdcaabaaaaaaaaaaaegaabaaaaaaaaaaakgakbaaaaaaaaaaadhaaaaaj
ccaabaaaaaaaaaaabkaabaaaaaaaaaaabkaabaaaacaaaaaackaabaaaacaaaaaa
dhaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaadkaabaaaacaaaaaabkaabaaa
aaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaklkkckdo
bkaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabaaaaahbcaabaaaaaaaaaaa
akaabaaaaaaaaaaaakaabaaaacaaaaaadeaaaaahccaabaaaaaaaaaaackaabaaa
abaaaaaabkaabaaaabaaaaaadeaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaa
akaabaaaabaaaaaaddaaaaahecaabaaaaaaaaaaackaabaaaabaaaaaabkaabaaa
abaaaaaaddaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaaakaabaaaabaaaaaa
aaaaaaaiecaabaaaaaaaaaaackaabaiaebaaaaaaaaaaaaaabkaabaaaaaaaaaaa
djaaaaahicaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaaaaaaoaaaaah
ecaabaaaaaaaaaaackaabaaaaaaaaaaabkaabaaaaaaaaaaaabaaaaahecaabaaa
aaaaaaaackaabaaaaaaaaaaadkaabaaaaaaaaaaadcaaaaaphcaabaaaacaaaaaa
agaabaaaaaaaaaaaaceaaaaaaaaamaeaaaaamaeaaaaamaeaaaaaaaaaaceaaaaa
aaaaeamaaaaaaamaaaaaiamaaaaaaaaadccaaabahcaabaaaacaaaaaaegacbaia
ibaaaaaaacaaaaaaaceaaaaaaaaaiadpaaaaialpaaaaialpaaaaaaaaaceaaaaa
aaaaialpaaaaaaeaaaaaaaeaaaaaaaaaaaaaaaakhcaabaaaacaaaaaaegacbaaa
acaaaaaaaceaaaaaaaaaialpaaaaialpaaaaialpaaaaaaaadcaaaaamncaabaaa
aaaaaaaaagajbaaaacaaaaaakgakbaaaaaaaaaaaaceaaaaaaaaaiadpaaaaaaaa
aaaaiadpaaaaiadpdiaaaaahncaabaaaaaaaaaaafgafbaaaaaaaaaaaagaobaaa
aaaaaaaaaaaaaaajccaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaiaebaaaaaa
aaaaaaaaapaaaaaadeaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaa
aaaaaaaaaaaaaaakicaabaaaabaaaaaaakiacaiaebaaaaaaaaaaaaaaapaaaaaa
bkiacaaaaaaaaaaaapaaaaaaaoaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaa
dkaabaaaabaaaaaaaaaaaaaiicaabaaaabaaaaaabkaabaiaebaaaaaaaaaaaaaa
abeaaaaaaaaaiadpdiaaaaahhcaabaaaaaaaaaaaigadbaaaaaaaaaaafgafbaaa
aaaaaaaadcaaaaajhccabaaaaaaaaaaapgapbaaaabaaaaaaegacbaaaabaaaaaa
egacbaaaaaaaaaaadgaaaaaficcabaaaaaaaaaaaabeaaaaaaaaaiadpdoaaaaab
"
}
SubProgram "d3d11 " {
Keywords { "DIRECTIONAL_COOKIE" }
SetTexture 0 [_CameraDepthTexture] 2D 1
SetTexture 1 [_Background] 2D 2
SetTexture 2 [Volume] 3D 0
ConstBuffer "$Globals" 256
Vector 112 [screenCorner]
Vector 128 [cameraUp]
Vector 144 [cameraRight]
Vector 160 [cameraWorldSize]
Float 176 [StepSize]
Vector 192 [worldOrigin]
Float 208 [halfWorldSize]
Float 212 [transparency]
Vector 224 [bored]
Float 240 [minF]
Float 244 [maxF]
ConstBuffer "UnityPerCamera" 128
Vector 64 [_WorldSpaceCameraPos] 3
Vector 112 [_ZBufferParams]
BindCB  "$Globals" 0
BindCB  "UnityPerCamera" 1
"ps_5_0
eefiecedlcnccghfojecddopdnnnaplnneenphpiabaaaaaagaalaaaaadaaaaaa
cmaaaaaaoeaaaaaabiabaaaaejfdeheolaaaaaaaagaaaaaaaiaaaaaajiaaaaaa
aaaaaaaaabaaaaaaadaaaaaaaaaaaaaaapaaaaaakeaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaabaaaaaaapalaaaakeaaaaaaabaaaaaaaaaaaaaaadaaaaaaacaaaaaa
ahahaaaakeaaaaaaacaaaaaaaaaaaaaaadaaaaaaadaaaaaaahaaaaaakeaaaaaa
adaaaaaaaaaaaaaaadaaaaaaaeaaaaaaahaaaaaakeaaaaaaaeaaaaaaaaaaaaaa
adaaaaaaafaaaaaaadaaaaaafdfgfpfaepfdejfeejepeoaafeeffiedepepfcee
aaklklklepfdeheocmaaaaaaabaaaaaaaiaaaaaacaaaaaaaaaaaaaaaaaaaaaaa
adaaaaaaaaaaaaaaapaaaaaafdfgfpfegbhcghgfheaaklklfdeieffieaakaaaa
faaaaaaajaacaaaagkaiaaabfjaaaaaeegiocaaaaaaaaaaabaaaaaaafjaaaaae
egiocaaaabaaaaaaaiaaaaaafkaaaaadaagabaaaaaaaaaaafkaaaaadaagabaaa
abaaaaaafkaaaaadaagabaaaacaaaaaafibiaaaeaahabaaaaaaaaaaaffffaaaa
fibiaaaeaahabaaaabaaaaaaffffaaaaficiaaaeaahabaaaacaaaaaaffffaaaa
gcbaaaadlcbabaaaabaaaaaagcbaaaadhcbabaaaacaaaaaagfaaaaadpccabaaa
aaaaaaaagiaaaaacafaaaaaaaoaaaaahdcaabaaaaaaaaaaaegbabaaaabaaaaaa
pgbpbaaaabaaaaaadiaaaaajhcaabaaaabaaaaaaegiccaaaaaaaaaaaaiaaaaaa
fgifcaaaaaaaaaaaakaaaaaadcaaaaakhcaabaaaabaaaaaaegacbaaaabaaaaaa
fgafbaaaaaaaaaaaegiccaaaaaaaaaaaahaaaaaadiaaaaajhcaabaaaacaaaaaa
egiccaaaaaaaaaaaajaaaaaaagiacaaaaaaaaaaaakaaaaaadcaaaaajhcaabaaa
abaaaaaaegacbaaaacaaaaaaagaabaaaaaaaaaaaegacbaaaabaaaaaaaaaaaaai
hcaabaaaacaaaaaaegacbaiaebaaaaaaabaaaaaaegbcbaaaacaaaaaabaaaaaah
ecaabaaaaaaaaaaaegacbaaaacaaaaaaegacbaaaacaaaaaaeeaaaaafecaabaaa
aaaaaaaackaabaaaaaaaaaaadiaaaaahhcaabaaaacaaaaaakgakbaaaaaaaaaaa
egacbaaaacaaaaaaefaaaailmcaaaaiaedffbfaaecaabaaaaaaaaaaaegaabaaa
aaaaaaaajghmbaaaaaaaaaaaaagabaaaabaaaaaaefaaaailmcaaaaiaedffbfaa
lcaabaaaaaaaaaaaegaabaaaaaaaaaaaeghlbaaaabaaaaaaaagabaaaacaaaaaa
dcaaaaalecaabaaaaaaaaaaackiacaaaabaaaaaaahaaaaaackaabaaaaaaaaaaa
dkiacaaaabaaaaaaahaaaaaaaoaaaaakecaabaaaaaaaaaaaaceaaaaaaaaaiadp
aaaaiadpaaaaiadpaaaaiadpckaabaaaaaaaaaaaaaaaaaajicaabaaaabaaaaaa
akiacaaaaaaaaaaaanaaaaaaakiacaaaaaaaaaaaanaaaaaadgaaaaafhcaabaaa
adaaaaaaegacbaaaabaaaaaadgaaaaaficaabaaaacaaaaaaabeaaaaaaaaaaaaa
dgaaaaaficaabaaaadaaaaaaabeaaaaaaaaaaaaadaaaaaabcbaaaaahbcaabaaa
aeaaaaaadkaabaaaadaaaaaaabeaaaaaaaabaaaaadaaaeadakaabaaaaeaaaaaa
aaaaaaajhcaabaaaaeaaaaaaegacbaiaebaaaaaaadaaaaaaegiccaaaabaaaaaa
aeaaaaaabaaaaaahbcaabaaaaeaaaaaaegacbaaaaeaaaaaaegacbaaaaeaaaaaa
elaaaaafbcaabaaaaeaaaaaaakaabaaaaeaaaaaabnaaaaahbcaabaaaaeaaaaaa
akaabaaaaeaaaaaackaabaaaaaaaaaaabpaaaeadakaabaaaaeaaaaaaacaaaaab
bfaaaaabaaaaaaajhcaabaaaaeaaaaaaegacbaaaadaaaaaaegiccaiaebaaaaaa
aaaaaaaaamaaaaaaaaaaaaaihcaabaaaaeaaaaaaegacbaaaaeaaaaaaagiacaaa
aaaaaaaaanaaaaaaaoaaaaahhcaabaaaaeaaaaaaegacbaaaaeaaaaaapgapbaaa
abaaaaaaeiaaaainecabaaiaedffbfaabcaabaaaaeaaaaaaegacbaaaaeaaaaaa
eghobaaaacaaaaaaaagabaaaaaaaaaaaabeaaaaaaaaaaaaadjaaaaahccaabaaa
aeaaaaaaakaabaaaaeaaaaaaabeaaaaaaaaaaaaacpaaaaagbcaabaaaaeaaaaaa
akaabaiaibaaaaaaaeaaaaaadiaaaaahbcaabaaaaeaaaaaaakaabaaaaeaaaaaa
abeaaaaajlcajkdoaaaaaaaibcaabaaaaeaaaaaaakaabaiambaaaaaaaeaaaaaa
abeaaaaaaaaaiadpabaaaaahbcaabaaaaeaaaaaaakaabaaaaeaaaaaabkaabaaa
aeaaaaaadiaaaaaibcaabaaaaeaaaaaaakaabaaaaeaaaaaabkiacaaaaaaaaaaa
anaaaaaaaaaaaaaiccaabaaaaeaaaaaadkaabaiaebaaaaaaacaaaaaaabeaaaaa
aaaaiadpdcaaaaajicaabaaaacaaaaaabkaabaaaaeaaaaaaakaabaaaaeaaaaaa
dkaabaaaacaaaaaadcaaaaakhcaabaaaadaaaaaaegacbaaaacaaaaaaagiacaaa
aaaaaaaaalaaaaaaegacbaaaadaaaaaaboaaaaahicaabaaaadaaaaaadkaabaaa
adaaaaaaabeaaaaaabaaaaaabgaaaaabaaaaaaaiecaabaaaaaaaaaaadkaabaia
ebaaaaaaacaaaaaaabeaaaaaaaaaiadpdiaaaaaihcaabaaaabaaaaaakgakbaaa
aaaaaaaaegiccaaaaaaaaaaaaoaaaaaadeaaaaahecaabaaaaaaaaaaadkaabaaa
aaaaaaaabkaabaaaaaaaaaaadeaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaa
akaabaaaaaaaaaaaddaaaaahicaabaaaabaaaaaadkaabaaaaaaaaaaabkaabaaa
aaaaaaaaddaaaaahicaabaaaabaaaaaaakaabaaaaaaaaaaadkaabaaaabaaaaaa
aaaaaaaiicaabaaaabaaaaaackaabaaaaaaaaaaadkaabaiaebaaaaaaabaaaaaa
djaaaaahbcaabaaaacaaaaaadkaabaaaabaaaaaaabeaaaaaaaaaaaaaaaaaaaai
ocaabaaaacaaaaaaaganbaiaebaaaaaaaaaaaaaakgakbaaaaaaaaaaaaoaaaaah
ocaabaaaacaaaaaafgaobaaaacaaaaaapgapbaaaabaaaaaaaaaaaaaiocaabaaa
acaaaaaapgajbaiaebaaaaaaacaaaaaafgaobaaaacaaaaaaaaaaaaakgcaabaaa
acaaaaaafgagbaaaacaaaaaaaceaaaaaaaaaaaaaaaaaaaeaaaaaiaeaaaaaaaaa
bnaaaaahdcaabaaaaaaaaaaaegaabaaaaaaaaaaakgakbaaaaaaaaaaadhaaaaaj
ccaabaaaaaaaaaaabkaabaaaaaaaaaaabkaabaaaacaaaaaackaabaaaacaaaaaa
dhaaaaajbcaabaaaaaaaaaaaakaabaaaaaaaaaaadkaabaaaacaaaaaabkaabaaa
aaaaaaaadiaaaaahbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabeaaaaaklkkckdo
bkaaaaafbcaabaaaaaaaaaaaakaabaaaaaaaaaaaabaaaaahbcaabaaaaaaaaaaa
akaabaaaaaaaaaaaakaabaaaacaaaaaadeaaaaahccaabaaaaaaaaaaackaabaaa
abaaaaaabkaabaaaabaaaaaadeaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaa
akaabaaaabaaaaaaddaaaaahecaabaaaaaaaaaaackaabaaaabaaaaaabkaabaaa
abaaaaaaddaaaaahecaabaaaaaaaaaaackaabaaaaaaaaaaaakaabaaaabaaaaaa
aaaaaaaiecaabaaaaaaaaaaackaabaiaebaaaaaaaaaaaaaabkaabaaaaaaaaaaa
djaaaaahicaabaaaaaaaaaaackaabaaaaaaaaaaaabeaaaaaaaaaaaaaaoaaaaah
ecaabaaaaaaaaaaackaabaaaaaaaaaaabkaabaaaaaaaaaaaabaaaaahecaabaaa
aaaaaaaackaabaaaaaaaaaaadkaabaaaaaaaaaaadcaaaaaphcaabaaaacaaaaaa
agaabaaaaaaaaaaaaceaaaaaaaaamaeaaaaamaeaaaaamaeaaaaaaaaaaceaaaaa
aaaaeamaaaaaaamaaaaaiamaaaaaaaaadccaaabahcaabaaaacaaaaaaegacbaia
ibaaaaaaacaaaaaaaceaaaaaaaaaiadpaaaaialpaaaaialpaaaaaaaaaceaaaaa
aaaaialpaaaaaaeaaaaaaaeaaaaaaaaaaaaaaaakhcaabaaaacaaaaaaegacbaaa
acaaaaaaaceaaaaaaaaaialpaaaaialpaaaaialpaaaaaaaadcaaaaamncaabaaa
aaaaaaaaagajbaaaacaaaaaakgakbaaaaaaaaaaaaceaaaaaaaaaiadpaaaaaaaa
aaaaiadpaaaaiadpdiaaaaahncaabaaaaaaaaaaafgafbaaaaaaaaaaaagaobaaa
aaaaaaaaaaaaaaajccaabaaaaaaaaaaabkaabaaaaaaaaaaaakiacaiaebaaaaaa
aaaaaaaaapaaaaaadeaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaaabeaaaaa
aaaaaaaaaaaaaaakicaabaaaabaaaaaaakiacaiaebaaaaaaaaaaaaaaapaaaaaa
bkiacaaaaaaaaaaaapaaaaaaaoaaaaahccaabaaaaaaaaaaabkaabaaaaaaaaaaa
dkaabaaaabaaaaaaaaaaaaaiicaabaaaabaaaaaabkaabaiaebaaaaaaaaaaaaaa
abeaaaaaaaaaiadpdiaaaaahhcaabaaaaaaaaaaaigadbaaaaaaaaaaafgafbaaa
aaaaaaaadcaaaaajhccabaaaaaaaaaaapgapbaaaabaaaaaaegacbaaaabaaaaaa
egacbaaaaaaaaaaadgaaaaaficcabaaaaaaaaaaaabeaaaaaaaaaiadpdoaaaaab
"
}
}
 }
}
Fallback "Transparent/VertexLit"
}